import { Agenda } from '../types';

export const mockAgendaData: Agenda[] = [
  {
    id: '1',
    slug: 'festival-wayang-kulit',
    event_name_id: 'Festival Wayang Kulit Yogyakarta',
    event_name_en: 'Yogyakarta Shadow Puppet Festival',
    description_id: 'Festival wayang kulit yang menampilkan dalang-dalang terbaik dari seluruh Jawa. Nikmati pertunjukan wayang dengan cerita klasik Ramayana dan Mahabharata, diiringi gamelan tradisional.',
    description_en: 'Shadow puppet festival featuring the best puppeteers from across Java. Enjoy wayang performances with classic Ramayana and Mahabharata stories, accompanied by traditional gamelan.',
    date_start: new Date('2024-12-15'),
    date_end: new Date('2024-12-17'),
    time_start: '19:00',
    time_end: '23:00',
    location: 'Keraton Yogyakarta',
    venue_name: 'Keraton Yogyakarta',
    images: ['/mock/wayang-festival1.jpg'],
    featured_image: '/mock/wayang-festival1.jpg',
    organizer: 'Keraton Yogyakarta',
    contact: { phone: '0274373721', email: 'info@kratonjogja.id' },
    price_type: 'free',
    category: 'Pertunjukan',
    category_id: 'Pertunjukan',
    category_en: 'Performance',
    status: 'published',
    published_at: new Date('2024-11-01'),
    created_at: new Date('2024-10-25'),
    updated_at: new Date('2024-11-05'),
  },
  {
    id: '2',
    slug: 'pameran-batik-nusantara',
    event_name_id: 'Pameran Batik Nusantara',
    event_name_en: 'Indonesian Batik Exhibition',
    description_id: 'Pameran batik dari berbagai daerah di Indonesia dengan workshop membatik untuk umum. Dapatkan kesempatan belajar langsung dari pengrajin batik berpengalaman.',
    description_en: 'Batik exhibition from various regions in Indonesia with public batik-making workshops. Get the opportunity to learn directly from experienced batik craftsmen.',
    date_start: new Date('2024-12-20'),
    date_end: new Date('2024-12-25'),
    time_start: '09:00',
    time_end: '17:00',
    location: 'Museum Batik Yogyakarta',
    venue_name: 'Museum Batik Yogyakarta',
    images: ['/mock/batik-exhibition1.jpg'],
    featured_image: '/mock/batik-exhibition1.jpg',
    organizer: 'Dinas Kebudayaan Yogyakarta',
    contact: { phone: '0274562628', email: 'info@museumbatik.id' },
    price_type: 'paid',
    price_amount: 25000,
    category: 'Pameran',
    category_id: 'Pameran',
    category_en: 'Exhibition',
    status: 'published',
    published_at: new Date('2024-11-15'),
    created_at: new Date('2024-11-10'),
    updated_at: new Date('2024-11-18'),
  },
  {
    id: '3',
    slug: 'pasar-seni-kuliner',
    event_name_id: 'Pasar Seni & Kuliner Tradisional',
    event_name_en: 'Traditional Art & Culinary Market',
    description_id: 'Pasar mingguan yang menampilkan produk seni dan kuliner khas Yogyakarta. Temukan kerajinan tangan unik dan makanan tradisional yang lezat.',
    description_en: 'Weekly market featuring traditional Yogyakarta art and culinary products. Discover unique handicrafts and delicious traditional foods.',
    date_start: new Date('2024-12-22'),
    date_end: new Date('2024-12-22'),
    time_start: '10:00',
    time_end: '22:00',
    location: 'Alun-alun Selatan',
    venue_name: 'Alun-alun Kidul',
    images: ['/mock/pasar-seni1.jpg'],
    featured_image: '/mock/pasar-seni1.jpg',
    organizer: 'Paguyuban Pedagang Alun-alun',
    contact: { phone: '081234567890' },
    price_type: 'free',
    category: 'Pasar',
    category_id: 'Pasar',
    category_en: 'Market',
    status: 'published',
    published_at: new Date('2024-11-20'),
    created_at: new Date('2024-11-15'),
    updated_at: new Date('2024-11-22'),
  },
  {
    id: '4',
    slug: 'sekaten-festival-2024',
    event_name_id: 'Festival Sekaten 2024',
    event_name_en: 'Sekaten Festival 2024',
    description_id: 'Perayaan tradisional memperingati kelahiran Nabi Muhammad SAW dengan pasar malam dan gamelan.',
    description_en: 'Traditional celebration commemorating the birth of Prophet Muhammad with night market and gamelan.',
    date_start: new Date('2024-03-15'),
    date_end: new Date('2024-03-22'),
    location: 'Alun-Alun Utara Keraton, Yogyakarta',
    venue_name: 'Keraton Yogyakarta',
    images: ['/mock/sekaten1.jpg'],
    featured_image: '/mock/sekaten1.jpg',
    organizer: 'Keraton Yogyakarta',
    contact: { phone: '0274123456', email: 'info@kraton.or.id' },
    price_type: 'free',
    category: 'Festival',
    category_id: 'Festival',
    category_en: 'Festival',
    status: 'published',
    published_at: new Date('2024-02-01'),
    created_at: new Date('2024-01-25'),
    updated_at: new Date('2024-02-05'),
  },
  {
    id: '5',
    slug: 'ramayana-ballet-march',
    event_name_id: 'Sendratari Ramayana',
    event_name_en: 'Ramayana Ballet',
    description_id: 'Pertunjukan tari klasik yang menceritakan kisah Ramayana dengan latar Candi Prambanan.',
    description_en: 'Classical dance performance depicting the Ramayana story with Prambanan Temple backdrop.',
    date_start: new Date('2024-03-10'),
    date_end: new Date('2024-03-10'),
    time_start: '19:30',
    time_end: '21:30',
    location: 'Candi Prambanan, Sleman',
    venue_name: 'Candi Prambanan',
    images: ['/mock/ramayana1.jpg'],
    featured_image: '/mock/ramayana1.jpg',
    organizer: 'PT Taman Wisata Candi',
    contact: { phone: '0274496401', email: 'info@borobudurpark.com' },
    price_type: 'paid',
    price_amount: 150000,
    registration_link: 'https://borobudurpark.com',
    category: 'Pertunjukan',
    category_id: 'Pertunjukan',
    category_en: 'Performance',
    status: 'published',
    published_at: new Date('2024-02-15'),
    created_at: new Date('2024-02-10'),
    updated_at: new Date('2024-02-18'),
  },
  {
    id: '6',
    slug: 'jogja-art-week-2024',
    event_name_id: 'Jogja Art Week 2024',
    event_name_en: 'Jogja Art Week 2024',
    description_id: 'Festival seni kontemporer dengan pameran, workshop, dan pertunjukan dari seniman lokal dan internasional.',
    description_en: 'Contemporary art festival with exhibitions, workshops, and performances from local and international artists.',
    date_start: new Date('2024-04-01'),
    date_end: new Date('2024-04-07'),
    location: 'Berbagai lokasi di Yogyakarta',
    images: ['/mock/artweek1.jpg'],
    featured_image: '/mock/artweek1.jpg',
    organizer: 'Jogja Art Community',
    contact: { phone: '081234567890', email: 'info@jogjaartweek.com' },
    price_type: 'free',
    category: 'Pameran',
    category_id: 'Pameran',
    category_en: 'Exhibition',
    status: 'published',
    published_at: new Date('2024-03-01'),
    created_at: new Date('2024-02-20'),
    updated_at: new Date('2024-03-05'),
  },
  {
    id: '7',
    slug: 'workshop-batik-cap',
    event_name_id: 'Workshop Batik Cap',
    event_name_en: 'Batik Stamping Workshop',
    description_id: 'Belajar teknik membatik dengan cap dan pewarnaan alami.',
    description_en: 'Learn batik stamping technique and natural dyeing.',
    date_start: new Date('2024-03-25'),
    date_end: new Date('2024-03-25'),
    time_start: '09:00',
    time_end: '15:00',
    location: 'Kampung Batik Giriloyo, Bantul',
    venue_name: 'Kampung Batik Giriloyo',
    images: ['/mock/workshop1.jpg'],
    featured_image: '/mock/workshop1.jpg',
    organizer: 'Paguyuban Batik Giriloyo',
    contact: { phone: '085678901234', email: 'batikgiriloyo@gmail.com' },
    price_type: 'paid',
    price_amount: 200000,
    category: 'Workshop',
    category_id: 'Workshop',
    category_en: 'Workshop',
    status: 'published',
    published_at: new Date('2024-03-01'),
    created_at: new Date('2024-02-25'),
    updated_at: new Date('2024-03-02'),
  },
  {
    id: '8',
    slug: 'gamelan-concert',
    event_name_id: 'Konser Gamelan Kontemporer',
    event_name_en: 'Contemporary Gamelan Concert',
    description_id: 'Konser gamelan dengan aransemen modern dan kolaborasi musik dunia.',
    description_en: 'Gamelan concert with modern arrangements and world music collaboration.',
    date_start: new Date('2024-03-30'),
    date_end: new Date('2024-03-30'),
    time_start: '19:00',
    time_end: '21:00',
    location: 'Gedung Societet Taman Budaya, Yogyakarta',
    venue_name: 'Taman Budaya Yogyakarta',
    images: ['/mock/gamelan1.jpg'],
    featured_image: '/mock/gamelan1.jpg',
    organizer: 'ISI Yogyakarta',
    contact: { phone: '0274562043', email: 'info@isi.ac.id' },
    price_type: 'paid',
    price_amount: 50000,
    category: 'Pertunjukan',
    category_id: 'Pertunjukan',
    category_en: 'Performance',
    status: 'published',
    published_at: new Date('2024-03-10'),
    created_at: new Date('2024-03-05'),
    updated_at: new Date('2024-03-12'),
  },
];
