import { Agenda } from '../types';

export const mockAgendaData: Agenda[] = [
  {
    id: '1',
    slug: 'sekaten-festival-2024',
    event_name_id: 'Festival Sekaten 2024',
    event_name_en: 'Sekaten Festival 2024',
    description_id: 'Perayaan tradisional memperingati kelahiran Nabi Muhammad SAW dengan pasar malam dan gamelan.',
    description_en: 'Traditional celebration commemorating the birth of Prophet Muhammad with night market and gamelan.',
    date_start: new Date('2024-03-15'),
    date_end: new Date('2024-03-22'),
    location: 'Alun-Alun Utara Keraton, Yogyakarta',
    venue_name: 'Keraton Yogyakarta',
    images: ['/mock/sekaten1.jpg'],
    featured_image: '/mock/sekaten1.jpg',
    organizer: 'Keraton Yogyakarta',
    contact: { phone: '0274123456', email: 'info@kraton.or.id' },
    price_type: 'free',
    category: 'Festival',
    status: 'published',
    published_at: new Date('2024-02-01'),
    created_at: new Date('2024-01-25'),
    updated_at: new Date('2024-02-05'),
  },
  {
    id: '2',
    slug: 'ramayana-ballet-march',
    event_name_id: 'Sendratari Ramayana',
    event_name_en: 'Ramayana Ballet',
    description_id: 'Pertunjukan tari klasik yang menceritakan kisah Ramayana dengan latar Candi Prambanan.',
    description_en: 'Classical dance performance depicting the Ramayana story with Prambanan Temple backdrop.',
    date_start: new Date('2024-03-10'),
    date_end: new Date('2024-03-10'),
    time_start: '19:30',
    time_end: '21:30',
    location: 'Candi Prambanan, Sleman',
    images: ['/mock/ramayana1.jpg'],
    featured_image: '/mock/ramayana1.jpg',
    organizer: 'PT Taman Wisata Candi',
    contact: { phone: '0274496401', email: 'info@borobudurpark.com' },
    price_type: 'paid',
    price_amount: 150000,
    registration_link: 'https://borobudurpark.com',
    category: 'Pertunjukan',
    status: 'published',
    published_at: new Date('2024-02-15'),
    created_at: new Date('2024-02-10'),
    updated_at: new Date('2024-02-18'),
  },
  {
    id: '3',
    slug: 'jogja-art-week-2024',
    event_name_id: 'Jogja Art Week 2024',
    event_name_en: 'Jogja Art Week 2024',
    description_id: 'Festival seni kontemporer dengan pameran, workshop, dan pertunjukan dari seniman lokal dan internasional.',
    description_en: 'Contemporary art festival with exhibitions, workshops, and performances from local and international artists.',
    date_start: new Date('2024-04-01'),
    date_end: new Date('2024-04-07'),
    location: 'Berbagai lokasi di Yogyakarta',
    images: ['/mock/artweek1.jpg'],
    featured_image: '/mock/artweek1.jpg',
    organizer: 'Jogja Art Community',
    contact: { phone: '081234567890', email: 'info@jogjaartweek.com' },
    price_type: 'free',
    category: 'Pameran',
    status: 'published',
    published_at: new Date('2024-03-01'),
    created_at: new Date('2024-02-20'),
    updated_at: new Date('2024-03-05'),
  },
  {
    id: '4',
    slug: 'workshop-batik-cap',
    event_name_id: 'Workshop Batik Cap',
    event_name_en: 'Batik Stamping Workshop',
    description_id: 'Belajar teknik membatik dengan cap dan pewarnaan alami.',
    description_en: 'Learn batik stamping technique and natural dyeing.',
    date_start: new Date('2024-03-25'),
    date_end: new Date('2024-03-25'),
    time_start: '09:00',
    time_end: '15:00',
    location: 'Kampung Batik Giriloyo, Bantul',
    images: ['/mock/workshop1.jpg'],
    featured_image: '/mock/workshop1.jpg',
    organizer: 'Paguyuban Batik Giriloyo',
    contact: { phone: '085678901234', email: 'batikgiriloyo@gmail.com' },
    price_type: 'paid',
    price_amount: 200000,
    category: 'Workshop',
    status: 'published',
    published_at: new Date('2024-03-01'),
    created_at: new Date('2024-02-25'),
    updated_at: new Date('2024-03-02'),
  },
  {
    id: '5',
    slug: 'gamelan-concert',
    event_name_id: 'Konser Gamelan Kontemporer',
    event_name_en: 'Contemporary Gamelan Concert',
    description_id: 'Konser gamelan dengan aransemen modern dan kolaborasi musik dunia.',
    description_en: 'Gamelan concert with modern arrangements and world music collaboration.',
    date_start: new Date('2024-03-30'),
    date_end: new Date('2024-03-30'),
    time_start: '19:00',
    time_end: '21:00',
    location: 'Gedung Societet Taman Budaya, Yogyakarta',
    venue_name: 'Taman Budaya Yogyakarta',
    images: ['/mock/gamelan1.jpg'],
    featured_image: '/mock/gamelan1.jpg',
    organizer: 'ISI Yogyakarta',
    contact: { phone: '0274562043', email: 'info@isi.ac.id' },
    price_type: 'paid',
    price_amount: 50000,
    category: 'Pertunjukan',
    status: 'draft',
    created_at: new Date('2024-03-10'),
    updated_at: new Date('2024-03-12'),
  },
];
