export interface FAQ {
  id: string;
  question_id: string;
  question_en: string;
  answer_id: string;
  answer_en: string;
  category_id: string;
  category_en: string;
  order: number;
  status: 'active' | 'inactive';
  created_at: Date;
  updated_at: Date;
}

// Data FAQ sinkron dengan FAQChat.tsx di halaman depan
export const mockFAQData: FAQ[] = [
  {
    id: '1',
    question_id: 'Apa itu Sumbu Filosofi Yogyakarta?',
    question_en: 'What is the Yogyakarta Philosophical Axis?',
    answer_id: 'Sumbu Filosofi adalah garis imajiner yang menghubungkan Tugu Yogyakarta, Keraton Yogyakarta, dan Panggung Krapyak. Garis ini melambangkan harmoni kosmologis dalam filosofi Jawa.',
    answer_en: 'The Philosophical Axis is an imaginary line connecting Tugu Yogyakarta, Yogyakarta Palace, and Panggung Krapyak. This line symbolizes cosmological harmony in Javanese philosophy.',
    category_id: 'Umum',
    category_en: 'General',
    order: 1,
    status: 'active',
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-02-15'),
  },
  {
    id: '2',
    question_id: 'Bagaimana cara mengakses peta interaktif?',
    question_en: 'How do I access the interactive map?',
    answer_id: 'Klik menu "Kawasan Sumbu Filosofi" di navigasi atas. Anda akan menemukan peta Google My Maps interaktif yang menampilkan semua titik penting di sepanjang sumbu.',
    answer_en: 'Click the "Philosophical Axis Area" menu in the top navigation. You will find an interactive Google My Maps showing all important points along the axis.',
    category_id: 'Navigasi',
    category_en: 'Navigation',
    order: 2,
    status: 'active',
    created_at: new Date('2024-01-15'),
    updated_at: new Date('2024-02-10'),
  },
  {
    id: '3',
    question_id: 'Dimana saya bisa melihat galeri foto?',
    question_en: 'Where can I view the photo gallery?',
    answer_id: 'Klik menu "Galeri Foto" atau tombol "Lihat Galeri" di halaman utama. Galeri menampilkan koleksi foto dengan filter berdasarkan kategori.',
    answer_en: 'Click the "Photo Gallery" menu or "View Gallery" button on the homepage. The gallery displays photo collections with category-based filters.',
    category_id: 'Navigasi',
    category_en: 'Navigation',
    order: 3,
    status: 'active',
    created_at: new Date('2024-01-20'),
    updated_at: new Date('2024-02-05'),
  },
  {
    id: '4',
    question_id: 'Bagaimana cara menemukan UMKM lokal?',
    question_en: 'How do I find local MSMEs?',
    answer_id: 'Buka halaman "Katalog UMKM" dari menu navigasi. Anda dapat memfilter UMKM berdasarkan kategori (Kerajinan, Kuliner, Fashion, Seni) dan lokasi.',
    answer_en: 'Open the "MSME Catalog" page from the navigation menu. You can filter MSMEs by category (Handicrafts, Culinary, Fashion, Arts) and location.',
    category_id: 'UMKM',
    category_en: 'MSME',
    order: 4,
    status: 'active',
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2024-02-20'),
  },
  {
    id: '5',
    question_id: 'Dimana informasi acara budaya?',
    question_en: 'Where can I find cultural event information?',
    answer_id: 'Kunjungi halaman "Agenda Seni & Budaya" untuk melihat kalender acara budaya yang akan datang di kawasan Sumbu Filosofi.',
    answer_en: 'Visit the "Arts & Culture Agenda" page to see the calendar of upcoming cultural events in the Philosophical Axis area.',
    category_id: 'Acara',
    category_en: 'Events',
    order: 5,
    status: 'active',
    created_at: new Date('2024-02-05'),
    updated_at: new Date('2024-02-25'),
  },
  {
    id: '6',
    question_id: 'Apa saja titik penting di Sumbu Filosofi?',
    question_en: 'What are the key points of the Philosophical Axis?',
    answer_id: 'Tiga titik utama: Tugu Yogyakarta (utara), Keraton Yogyakarta (pusat), dan Panggung Krapyak (selatan). Sumbu ini membentang dari utara ke selatan sebagai representasi filosofis perjalanan hidup.',
    answer_en: 'Three main points: Tugu Yogyakarta (north), Yogyakarta Palace (center), and Panggung Krapyak (south). This axis stretches from north to south as a philosophical representation of life\'s journey.',
    category_id: 'Umum',
    category_en: 'General',
    order: 6,
    status: 'active',
    created_at: new Date('2024-02-08'),
    updated_at: new Date('2024-02-28'),
  },
  {
    id: '7',
    question_id: 'Bagaimana cara menghubungi untuk kolaborasi acara?',
    question_en: 'How do I contact for event collaboration?',
    answer_id: 'Anda dapat menghubungi kami melalui email info@sumbufilosofi.id atau melalui tombol "Hubungi Kami" di halaman Agenda Seni & Budaya.',
    answer_en: 'You can contact us via email at info@sumbufilosofi.id or through the "Contact Us" button on the Arts & Culture Agenda page.',
    category_id: 'Kontak',
    category_en: 'Contact',
    order: 7,
    status: 'active',
    created_at: new Date('2024-02-10'),
    updated_at: new Date('2024-03-01'),
  },
  {
    id: '8',
    question_id: 'Apakah website ini tersedia dalam bahasa Inggris?',
    question_en: 'Is this website available in English?',
    answer_id: 'Ya! Klik tombol bendera di pojok kanan atas untuk beralih antara Bahasa Indonesia dan English.',
    answer_en: 'Yes! Click the flag button in the top right corner to switch between Bahasa Indonesia and English.',
    category_id: 'Navigasi',
    category_en: 'Navigation',
    order: 8,
    status: 'active',
    created_at: new Date('2024-02-12'),
    updated_at: new Date('2024-03-03'),
  },
  {
    id: '9',
    question_id: 'Apa makna filosofis Sumbu ini?',
    question_en: 'What is the philosophical meaning of this Axis?',
    answer_id: 'Bukan sekadar garis geografis, tetapi merupakan representasi mendalam dari perjalanan hidup manusia - dari kelahiran hingga kembali kepada Sang Pencipta, dengan setiap lokasi dan vegetasi memiliki makna filosofis yang mendalam.',
    answer_en: 'More than just a geographical line, it is a profound representation of the human life journey - from birth to returning to the Creator, with each location and vegetation having deep philosophical meaning.',
    category_id: 'Umum',
    category_en: 'General',
    order: 9,
    status: 'active',
    created_at: new Date('2024-02-15'),
    updated_at: new Date('2024-03-05'),
  },
  {
    id: '10',
    question_id: 'Bagaimana cara filter galeri foto?',
    question_en: 'How do I filter the photo gallery?',
    answer_id: 'Di halaman Galeri Foto, gunakan tombol filter di bagian atas untuk memilih kategori: Kawasan, Sejarah, Wisata, UMKM, atau Agenda. Klik "Semua" untuk melihat semua foto.',
    answer_en: 'On the Photo Gallery page, use the filter buttons at the top to select categories: Area, History, Tourism, MSME, or Events. Click "All" to view all photos.',
    category_id: 'Navigasi',
    category_en: 'Navigation',
    order: 10,
    status: 'active',
    created_at: new Date('2024-02-18'),
    updated_at: new Date('2024-03-08'),
  },
  {
    id: '11',
    question_id: 'Apakah UMKM yang terdaftar sudah terverifikasi?',
    question_en: 'Are the registered MSMEs verified?',
    answer_id: 'Ya, semua UMKM yang terdaftar di katalog sudah melalui proses kurasi oleh admin untuk memastikan kualitas dan keaslian.',
    answer_en: 'Yes, all MSMEs listed in the catalog have gone through a curation process by admins to ensure quality and authenticity.',
    category_id: 'UMKM',
    category_en: 'MSME',
    order: 11,
    status: 'active',
    created_at: new Date('2024-02-20'),
    updated_at: new Date('2024-03-10'),
  },
];
