import { Galeri } from '../types';

export const mockGaleriData: Galeri[] = [
  {
    id: '1',
    slug: 'keraton-yogyakarta-sunset',
    title_id: 'Keraton Yogyakarta - Pusat Sumbu Filosofi',
    title_en: 'Yogyakarta Palace - Center of Philosophical Axis',
    description_id: 'Pemandangan Keraton Yogyakarta yang megah diterangi cahaya senja keemasan',
    description_en: 'Magnificent view of Yogyakarta Palace illuminated by golden sunset light',
    image_url: 'https://images.unsplash.com/photo-1655793488799-1ffba5b22cbd?w=1080',
    category: 'Kawasan',
    tags: ['keraton', 'heritage', 'palace'],
    alt_text_id: 'Keraton Yogyakarta dengan langit jingga',
    alt_text_en: 'Yogyakarta Palace with orange sky',
    photographer: 'Budi Santoso',
    status: 'published',
    published_at: new Date('2024-02-10'),
    created_at: new Date('2024-02-08'),
    updated_at: new Date('2024-02-10'),
  },
  {
    id: '2',
    slug: 'tugu-jogja-malam-hari',
    title_id: 'Tugu Jogja di Malam Hari',
    title_en: 'Tugu Jogja at Night',
    description_id: 'Monumen Tugu dengan pencahayaan malam yang indah dan lalu lintas kota',
    description_en: 'Tugu Monument with beautiful night lighting and city traffic',
    image_url: '/mock/gallery/tugu-night.jpg',
    category: 'Kawasan',
    tags: ['tugu', 'night', 'landmark', 'city'],
    photographer: 'Andi Wijaya',
    status: 'published',
    published_at: new Date('2024-02-12'),
    created_at: new Date('2024-02-11'),
    updated_at: new Date('2024-02-12'),
  },
  {
    id: '3',
    slug: 'batik-tulis-proses',
    title_id: 'Kerajinan Batik Tradisional',
    title_en: 'Traditional Batik Craft',
    description_id: 'Pengrajin sedang membuat batik tulis dengan canting dan malam',
    description_en: 'Craftsman creating hand-drawn batik with canting and wax',
    image_url: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=1080',
    category: 'UMKM',
    tags: ['batik', 'craft'],
    photographer: 'Siti Rahayu',
    status: 'published',
    published_at: new Date('2024-02-08'),
    created_at: new Date('2024-02-05'),
    updated_at: new Date('2024-02-08'),
  },
  {
    id: '4',
    slug: 'wayang-kulit-performance',
    title_id: 'Pertunjukan Wayang Kulit',
    title_en: 'Shadow Puppet Performance',
    description_id: 'Pertunjukan wayang kulit tradisional dengan dalang di belakang layar',
    description_en: 'Traditional shadow puppet performance with puppeteer behind the screen',
    image_url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1080',
    category: 'Agenda',
    tags: ['wayang', 'performance'],
    photographer: 'Agus Pramono',
    status: 'published',
    published_at: new Date('2024-01-28'),
    created_at: new Date('2024-01-25'),
    updated_at: new Date('2024-01-28'),
  },
  {
    id: '5',
    slug: 'tugu-yogyakarta',
    title_id: 'Tugu Yogyakarta',
    title_en: 'Yogyakarta Monument',
    description_id: 'Monumen Tugu yang megah sebagai landmark kota Yogyakarta',
    description_en: 'Magnificent Tugu Monument as Yogyakarta city landmark',
    image_url: 'https://images.unsplash.com/photo-1675475904342-47d71467df1a?w=1080',
    category: 'Wisata',
    tags: ['monument', 'landmark'],
    photographer: 'Dewi Lestari',
    status: 'published',
    published_at: new Date('2024-02-15'),
    created_at: new Date('2024-02-14'),
    updated_at: new Date('2024-02-15'),
  },
  {
    id: '6',
    slug: 'malioboro-street',
    title_id: 'Jalan Malioboro',
    title_en: 'Malioboro Street',
    description_id: 'Suasana ramai Jalan Malioboro dengan pedagang dan wisatawan',
    description_en: 'Bustling atmosphere of Malioboro Street with vendors and tourists',
    image_url: '/mock/gallery/malioboro.jpg',
    category: 'Wisata',
    tags: ['malioboro', 'shopping', 'street', 'tourism'],
    status: 'published',
    published_at: new Date('2024-02-05'),
    created_at: new Date('2024-02-03'),
    updated_at: new Date('2024-02-05'),
  },
  {
    id: '7',
    slug: 'gudeg-traditional-dish',
    title_id: 'Gudeg Khas Yogyakarta',
    title_en: 'Traditional Gudeg Dish',
    description_id: 'Sepiring gudeg lengkap dengan ayam, telur, dan krecek',
    description_en: 'A plate of complete gudeg with chicken, egg, and krecek',
    image_url: '/mock/gallery/gudeg.jpg',
    category: 'UMKM',
    tags: ['gudeg', 'food', 'culinary', 'traditional'],
    photographer: 'Rini Kusuma',
    status: 'published',
    published_at: new Date('2024-02-01'),
    created_at: new Date('2024-01-30'),
    updated_at: new Date('2024-02-01'),
  },
  {
    id: '8',
    slug: 'sekaten-festival',
    title_id: 'Festival Sekaten',
    title_en: 'Sekaten Festival',
    description_id: 'Perayaan Sekaten di Alun-Alun Utara Keraton Yogyakarta',
    description_en: 'Sekaten celebration at the North Square of Yogyakarta Palace',
    image_url: '/mock/gallery/sekaten.jpg',
    category: 'Agenda',
    tags: ['sekaten', 'festival', 'tradition', 'celebration'],
    photographer: 'Hadi Wijaya',
    status: 'published',
    published_at: new Date('2024-01-20'),
    created_at: new Date('2024-01-18'),
    updated_at: new Date('2024-01-20'),
  },
  {
    id: '9',
    slug: 'silverware-kotagede',
    title_id: 'Kerajinan Perak Kotagede',
    title_en: 'Kotagede Silverware',
    description_id: 'Hasil kerajinan perak halus khas Kotagede',
    description_en: 'Fine silver crafts typical of Kotagede',
    image_url: '/mock/gallery/silver-craft.jpg',
    category: 'UMKM',
    tags: ['silver', 'handicraft', 'kotagede', 'jewelry'],
    photographer: 'Bambang Sutrisno',
    status: 'published',
    published_at: new Date('2024-02-18'),
    created_at: new Date('2024-02-16'),
    updated_at: new Date('2024-02-18'),
  },
  {
    id: '10',
    slug: 'pantai-parangtritis',
    title_id: 'Pantai Parangtritis',
    title_en: 'Parangtritis Beach',
    description_id: 'Pemandangan pantai Parangtritis dengan bukit pasir dan ombak',
    description_en: 'View of Parangtritis Beach with sand dunes and waves',
    image_url: '/mock/gallery/parangtritis.jpg',
    category: 'Wisata',
    tags: ['beach', 'parangtritis', 'nature', 'landscape'],
    status: 'published',
    published_at: new Date('2024-02-14'),
    created_at: new Date('2024-02-12'),
    updated_at: new Date('2024-02-14'),
  },
  {
    id: '11',
    slug: 'tari-bedhaya',
    title_id: 'Tari Bedhaya Keraton',
    title_en: 'Bedhaya Court Dance',
    description_id: 'Penari Bedhaya dengan kostum tradisional di pendopo keraton',
    description_en: 'Bedhaya dancers in traditional costumes at palace pavilion',
    image_url: '/mock/gallery/bedhaya-dance.jpg',
    category: 'Budaya',
    tags: ['dance', 'bedhaya', 'traditional', 'keraton'],
    photographer: 'Retno Wulandari',
    status: 'published',
    published_at: new Date('2024-01-25'),
    created_at: new Date('2024-01-23'),
    updated_at: new Date('2024-01-25'),
  },
  {
    id: '12',
    slug: 'angkringan-night',
    title_id: 'Angkringan Malam Hari',
    title_en: 'Night Angkringan',
    description_id: 'Suasana angkringan dengan lampu remang dan pengunjung',
    description_en: 'Angkringan atmosphere with dim lights and visitors',
    image_url: '/mock/gallery/angkringan.jpg',
    category: 'UMKM',
    tags: ['angkringan', 'food', 'night', 'street-food'],
    status: 'published',
    published_at: new Date('2024-02-06'),
    created_at: new Date('2024-02-04'),
    updated_at: new Date('2024-02-06'),
  },
  {
    id: '13',
    slug: 'ramayana-ballet',
    title_id: 'Sendratari Ramayana',
    title_en: 'Ramayana Ballet',
    description_id: 'Pertunjukan Sendratari Ramayana di Candi Prambanan',
    description_en: 'Ramayana Ballet performance at Prambanan Temple',
    image_url: '/mock/gallery/ramayana-ballet.jpg',
    category: 'Agenda',
    tags: ['ramayana', 'ballet', 'performance', 'prambanan'],
    photographer: 'Eko Prasetyo',
    status: 'published',
    published_at: new Date('2024-01-30'),
    created_at: new Date('2024-01-28'),
    updated_at: new Date('2024-01-30'),
  },
  {
    id: '14',
    slug: 'alun-alun-kidul',
    title_id: 'Alun-Alun Kidul',
    title_en: 'South Square',
    description_id: 'Suasana Alun-Alun Kidul dengan pohon beringin kembar',
    description_en: 'South Square atmosphere with twin banyan trees',
    image_url: '/mock/gallery/alun-alun.jpg',
    category: 'Kawasan',
    tags: ['alun-alun', 'square', 'landmark', 'recreation'],
    status: 'published',
    published_at: new Date('2024-02-09'),
    created_at: new Date('2024-02-07'),
    updated_at: new Date('2024-02-09'),
  },
  {
    id: '15',
    slug: 'gamelan-orchestra',
    title_id: 'Orkestra Gamelan',
    title_en: 'Gamelan Orchestra',
    description_id: 'Perangkat gamelan lengkap dengan pemain musik tradisional',
    description_en: 'Complete gamelan set with traditional music players',
    image_url: '/mock/gallery/gamelan.jpg',
    category: 'Budaya',
    tags: ['gamelan', 'music', 'traditional', 'orchestra'],
    status: 'draft',
    created_at: new Date('2024-02-19'),
    updated_at: new Date('2024-02-20'),
  },
];
