import { Kawasan } from '../types';

export const mockKawasanData: Kawasan[] = [
  {
    id: '1',
    slug: 'keraton-yogyakarta',
    name_id: 'Keraton Ngayogyakarta Hadiningrat',
    name_en: 'Yogyakarta Palace',
    description_id: 'Istana resmi Kesultanan Yogyakarta yang masih berfungsi sebagai pusat pemerintahan dan budaya Jawa.',
    description_en: 'The official palace of the Yogyakarta Sultanate, still functioning as the center of Javanese government and culture.',
    history_id: 'Didirikan oleh Sultan Hamengku Buwono I pada tahun 1755, Keraton menjadi simbol kedaulatan dan identitas budaya Yogyakarta.',
    history_en: 'Founded by Sultan Hamengku Buwono I in 1755, the Palace became a symbol of sovereignty and cultural identity of Yogyakarta.',
    category: 'Keraton',
    address: 'Jl. Rotowijayan Blok No. 1, Panembahan',
    district: 'Kraton',
    coordinates: { lat: -7.8052, lng: 110.3644 },
    images: ['/mock/keraton1.jpg', '/mock/keraton2.jpg'],
    featured_image: '/mock/keraton1.jpg',
    operating_hours: {
      open_time: '08:00',
      close_time: '14:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 15000,
    contact: { phone: '0274373721', email: 'info@kratonjogja.id' },
    facilities: ['Toilet', 'Parkir', 'Mushola', 'Kantin', 'Toko Souvenir'],
    accessibility: ['Kursi Roda', 'Jalur Landai'],
    best_visit_time: 'Pagi hari (08:00-11:00) untuk menghindari panas dan keramaian',
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-15'),
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-02-20'),
  },
  {
    id: '2',
    slug: 'candi-prambanan',
    name_id: 'Candi Prambanan',
    name_en: 'Prambanan Temple',
    description_id: 'Kompleks candi Hindu terbesar di Indonesia yang dibangun pada abad ke-9, terkenal dengan arsitektur megahnya.',
    description_en: 'The largest Hindu temple complex in Indonesia built in the 9th century, famous for its magnificent architecture.',
    history_id: 'Dibangun sekitar tahun 850 M oleh Rakai Pikatan dari Wangsa Sanjaya, sebagai tandingan Candi Borobudur yang dibangun Wangsa Syailendra.',
    history_en: 'Built around 850 AD by Rakai Pikatan of the Sanjaya dynasty, as a counterpart to Borobudur Temple built by the Syailendra dynasty.',
    category: 'Candi',
    address: 'Jl. Raya Jogja - Solo KM 16, Prambanan',
    district: 'Sleman',
    coordinates: { lat: -7.7520, lng: 110.4915 },
    images: ['/mock/prambanan1.jpg', '/mock/prambanan2.jpg', '/mock/prambanan3.jpg'],
    featured_image: '/mock/prambanan1.jpg',
    operating_hours: {
      open_time: '06:30',
      close_time: '17:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 50000,
    contact: { phone: '0274496401', email: 'info@borobudurpark.com' },
    facilities: ['Toilet', 'Parkir Luas', 'Mushola', 'Restoran', 'Toko Souvenir', 'Area Foto'],
    accessibility: ['Jalur Landai', 'Toilet Disabilitas'],
    best_visit_time: 'Sore hari (15:00-17:00) untuk sunset atau pagi hari (06:30-08:00)',
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-12'),
    created_at: new Date('2024-01-08'),
    updated_at: new Date('2024-02-15'),
  },
  {
    id: '3',
    slug: 'alun-alun-kidul',
    name_id: 'Alun-alun Kidul',
    name_en: 'South Square',
    description_id: 'Lapangan terbuka di selatan Keraton yang menjadi pusat aktivitas masyarakat dan wisata malam dengan becak hias.',
    description_en: 'An open field south of the Palace that serves as a center for community activities and night tourism with decorated pedicabs.',
    history_id: 'Alun-alun Kidul memiliki dua pohon beringin kembar yang dipercaya sebagai tempat keramat. Tradisi masangin (berjalan di antara dua pohon dengan mata tertutup) masih dilakukan hingga kini.',
    history_en: 'Alun-alun Kidul has two twin banyan trees believed to be a sacred place. The masangin tradition (walking between the two trees with eyes closed) is still practiced today.',
    category: 'Alun-alun',
    address: 'Jl. Patehan Lor, Patehan',
    district: 'Kraton',
    coordinates: { lat: -7.8113, lng: 110.3642 },
    images: ['/mock/alunkidul1.jpg', '/mock/alunkidul2.jpg'],
    featured_image: '/mock/alunkidul1.jpg',
    operating_hours: {
      open_time: '00:00',
      close_time: '23:59',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'free',
    facilities: ['Toilet', 'Parkir', 'Warung Makan', 'Becak Hias'],
    best_visit_time: 'Malam hari (18:00-22:00) untuk suasana meriah dengan lampu warna-warni',
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-20'),
    created_at: new Date('2024-01-18'),
    updated_at: new Date('2024-02-10'),
  },
  {
    id: '4',
    slug: 'tugu-yogyakarta',
    name_id: 'Tugu Yogyakarta',
    name_en: 'Yogyakarta Monument',
    description_id: 'Tugu berbentuk gilig (silinder) yang menjadi ikon dan landmark kota Yogyakarta, terletak di perempatan nol kilometer.',
    description_en: 'A gilig-shaped (cylindrical) monument that serves as an icon and landmark of Yogyakarta city, located at the zero kilometer intersection.',
    history_id: 'Dibangun oleh Sultan Hamengku Buwono I pada tahun 1755 sebagai Garis Imajiner yang menghubungkan Laut Selatan, Keraton, dan Gunung Merapi.',
    history_en: 'Built by Sultan Hamengku Buwono I in 1755 as an Imaginary Line connecting the South Sea, the Palace, and Mount Merapi.',
    category: 'Tugu',
    address: 'Jl. Jenderal Sudirman, Ngupasan',
    district: 'Gondomanan',
    coordinates: { lat: -7.7830, lng: 110.3669 },
    images: ['/mock/tugu1.jpg', '/mock/tugu2.jpg'],
    featured_image: '/mock/tugu1.jpg',
    operating_hours: {
      open_time: '00:00',
      close_time: '23:59',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'free',
    facilities: ['Taman', 'Area Foto', 'Jalur Pejalan Kaki'],
    best_visit_time: 'Malam hari (18:00-21:00) saat tugu diterangi lampu atau pagi hari untuk foto',
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-18'),
    created_at: new Date('2024-01-15'),
    updated_at: new Date('2024-02-12'),
  },
  {
    id: '5',
    slug: 'kampung-kotagede',
    name_id: 'Kampung Kotagede',
    name_en: 'Kotagede Heritage Village',
    description_id: 'Pusat kerajinan perak dan kawasan bersejarah bekas ibu kota Kerajaan Mataram Islam dengan arsitektur tradisional.',
    description_en: 'Center of silver craftsmanship and historic area, former capital of the Islamic Mataram Kingdom with traditional architecture.',
    history_id: 'Kotagede didirikan oleh Panembahan Senopati sebagai ibu kota Kerajaan Mataram pada akhir abad ke-16. Makam para raja Mataram berada di komplek ini.',
    history_en: 'Kotagede was founded by Panembahan Senopati as the capital of the Mataram Kingdom in the late 16th century. The tombs of Mataram kings are located in this complex.',
    category: 'Kampung',
    address: 'Kotagede',
    district: 'Kotagede',
    coordinates: { lat: -7.8280, lng: 110.3990 },
    images: ['/mock/kotagede1.jpg', '/mock/kotagede2.jpg'],
    featured_image: '/mock/kotagede1.jpg',
    operating_hours: {
      open_time: '08:00',
      close_time: '17:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'free',
    contact: { phone: '081234567890' },
    facilities: ['Toko Perak', 'Warung Tradisional', 'Makam Raja', 'Masjid Kuno'],
    best_visit_time: 'Pagi hingga sore (09:00-16:00) untuk mengunjungi workshop perak',
    featured: false,
    status: 'published',
    published_at: new Date('2024-02-01'),
    created_at: new Date('2024-01-28'),
    updated_at: new Date('2024-02-18'),
  },
  {
    id: '6',
    slug: 'museum-sonobudoyo',
    name_id: 'Museum Sonobudoyo',
    name_en: 'Sonobudoyo Museum',
    description_id: 'Museum yang menyimpan koleksi budaya Jawa terlengkap termasuk wayang, keris, topeng, dan arca kuno.',
    description_en: 'Museum housing the most complete collection of Javanese culture including wayang, keris, masks, and ancient statues.',
    history_id: 'Didirikan pada tahun 1935 oleh Yayasan Sonobudoyo. Museum ini merupakan salah satu museum terlengkap di Indonesia dengan koleksi lebih dari 43.000 benda.',
    history_en: 'Founded in 1935 by the Sonobudoyo Foundation. This museum is one of the most complete museums in Indonesia with a collection of more than 43,000 objects.',
    category: 'Museum',
    address: 'Jl. Pangurakan No. 6, Ngupasan',
    district: 'Gondomanan',
    coordinates: { lat: -7.8029, lng: 110.3656 },
    images: ['/mock/sonobudoyo1.jpg', '/mock/sonobudoyo2.jpg'],
    featured_image: '/mock/sonobudoyo1.jpg',
    operating_hours: {
      open_time: '08:00',
      close_time: '15:30',
      days: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 10000,
    contact: { phone: '0274376175', email: 'info@sonobudoyo.com' },
    facilities: ['Toilet', 'Parkir', 'Perpustakaan', 'Toko Souvenir', 'Ruang Audio Visual'],
    accessibility: ['Jalur Landai'],
    best_visit_time: 'Pagi hari (08:00-11:00) untuk tour yang lebih tenang',
    featured: false,
    status: 'published',
    published_at: new Date('2024-02-05'),
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2024-02-22'),
  },
  {
    id: '7',
    slug: 'benteng-vredeburg',
    name_id: 'Benteng Vredeburg',
    name_en: 'Fort Vredeburg',
    description_id: 'Benteng peninggalan Belanda yang kini menjadi Museum Sejarah Perjuangan Kemerdekaan Indonesia.',
    description_en: 'A Dutch colonial fortress now serving as the Museum of Indonesian Struggle for Independence History.',
    history_id: 'Dibangun pada tahun 1760 oleh Sri Sultan Hamengku Buwono I atas permintaan Belanda. Benteng ini menjadi saksi perjuangan kemerdekaan Indonesia.',
    history_en: 'Built in 1760 by Sri Sultan Hamengku Buwono I at the request of the Dutch. This fort witnessed the struggle for Indonesian independence.',
    category: 'Museum',
    address: 'Jl. Margo Mulyo No. 6, Ngupasan',
    district: 'Gondomanan',
    coordinates: { lat: -7.8000, lng: 110.3660 },
    images: ['/mock/vredeburg1.jpg', '/mock/vredeburg2.jpg'],
    featured_image: '/mock/vredeburg1.jpg',
    operating_hours: {
      open_time: '08:00',
      close_time: '16:00',
      days: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 5000,
    contact: { phone: '0274586934', email: 'vredeburg@kemdikbud.go.id' },
    facilities: ['Toilet', 'Parkir', 'Mushola', 'Perpustakaan', 'Auditorium', 'Wifi Gratis'],
    accessibility: ['Kursi Roda', 'Jalur Landai', 'Toilet Disabilitas'],
    best_visit_time: 'Pagi hingga siang (08:00-14:00)',
    featured: false,
    status: 'draft',
    created_at: new Date('2024-03-01'),
    updated_at: new Date('2024-03-05'),
  },
];
