export interface MediaFile {
  id: string;
  filename: string;
  url: string;
  type: 'image' | 'video' | 'document';
  mime_type: string;
  size: number;
  dimensions?: {
    width: number;
    height: number;
  };
  uploaded_by: string;
  uploaded_at: Date;
  alt_text?: string;
  caption?: string;
  used_in: string[];
}

export const mockMediaData: MediaFile[] = [
  {
    id: '1',
    filename: 'keraton-yogyakarta-sunset.jpg',
    url: '/mock/keraton-sunset.jpg',
    type: 'image',
    mime_type: 'image/jpeg',
    size: 2458624,
    dimensions: { width: 1920, height: 1080 },
    uploaded_by: 'Admin User',
    uploaded_at: new Date('2024-03-15T10:30:00'),
    alt_text: 'Pemandangan sunset di Keraton Yogyakarta',
    caption: 'Keraton Yogyakarta saat matahari terbenam',
    used_in: ['Galeri', 'Kawasan'],
  },
  {
    id: '2',
    filename: 'tugu-jogja-night.jpg',
    url: '/mock/tugu-night.jpg',
    type: 'image',
    mime_type: 'image/jpeg',
    size: 1876543,
    dimensions: { width: 1600, height: 1200 },
    uploaded_by: 'Admin User',
    uploaded_at: new Date('2024-03-14T15:20:00'),
    alt_text: 'Tugu Yogyakarta di malam hari',
    used_in: ['Galeri', 'Kawasan'],
  },
  {
    id: '3',
    filename: 'batik-proses-pewarnaan.jpg',
    url: '/mock/batik-process.jpg',
    type: 'image',
    mime_type: 'image/jpeg',
    size: 3125478,
    dimensions: { width: 2048, height: 1536 },
    uploaded_by: 'Admin User',
    uploaded_at: new Date('2024-03-13T09:15:00'),
    alt_text: 'Proses pewarnaan batik tradisional',
    caption: 'Pengrajin batik sedang melakukan pewarnaan',
    used_in: ['UMKM', 'Galeri'],
  },
  {
    id: '4',
    filename: 'prambanan-temple-sunrise.jpg',
    url: '/mock/prambanan-sunrise.jpg',
    type: 'image',
    mime_type: 'image/jpeg',
    size: 2987654,
    dimensions: { width: 2400, height: 1600 },
    uploaded_by: 'Editor User',
    uploaded_at: new Date('2024-03-12T06:45:00'),
    alt_text: 'Candi Prambanan saat sunrise',
    caption: 'Keindahan Candi Prambanan di pagi hari',
    used_in: ['Kawasan', 'Wisata', 'Galeri'],
  },
  {
    id: '5',
    filename: 'gudeg-yu-djum.jpg',
    url: '/mock/gudeg-dish.jpg',
    type: 'image',
    mime_type: 'image/jpeg',
    size: 1456789,
    dimensions: { width: 1280, height: 720 },
    uploaded_by: 'Admin User',
    uploaded_at: new Date('2024-03-11T12:00:00'),
    alt_text: 'Hidangan gudeg khas Yogyakarta',
    caption: 'Gudeg Yu Djum dengan nasi dan pelengkapnya',
    used_in: ['UMKM', 'Galeri'],
  },
  {
    id: '6',
    filename: 'wayang-kulit-performance.jpg',
    url: '/mock/wayang-performance.jpg',
    type: 'image',
    mime_type: 'image/jpeg',
    size: 2156789,
    dimensions: { width: 1800, height: 1200 },
    uploaded_by: 'Admin User',
    uploaded_at: new Date('2024-03-10T19:30:00'),
    alt_text: 'Pertunjukan wayang kulit',
    caption: 'Dalang sedang memainkan wayang kulit',
    used_in: ['Agenda', 'Galeri'],
  },
  {
    id: '7',
    filename: 'malioboro-street-evening.jpg',
    url: '/mock/malioboro-evening.jpg',
    type: 'image',
    mime_type: 'image/jpeg',
    size: 2678901,
    dimensions: { width: 1920, height: 1280 },
    uploaded_by: 'Editor User',
    uploaded_at: new Date('2024-03-09T18:15:00'),
    alt_text: 'Jalan Malioboro di sore hari',
    caption: 'Suasana ramai Malioboro saat sore',
    used_in: ['Wisata', 'Galeri'],
  },
  {
    id: '8',
    filename: 'pantai-parangtritis-sunset.jpg',
    url: '/mock/parangtritis-beach.jpg',
    type: 'image',
    mime_type: 'image/jpeg',
    size: 3456789,
    dimensions: { width: 2560, height: 1440 },
    uploaded_by: 'Admin User',
    uploaded_at: new Date('2024-03-08T17:00:00'),
    alt_text: 'Sunset di Pantai Parangtritis',
    caption: 'Keindahan sunset Pantai Parangtritis',
    used_in: ['Wisata', 'Galeri'],
  },
  {
    id: '9',
    filename: 'sekaten-festival.jpg',
    url: '/mock/sekaten-festival.jpg',
    type: 'image',
    mime_type: 'image/jpeg',
    size: 2234567,
    dimensions: { width: 1600, height: 900 },
    uploaded_by: 'Admin User',
    uploaded_at: new Date('2024-03-07T14:30:00'),
    alt_text: 'Festival Sekaten di Alun-alun Utara',
    caption: 'Keramaian Festival Sekaten',
    used_in: ['Agenda', 'Galeri'],
  },
  {
    id: '10',
    filename: 'silver-craft-kotagede.jpg',
    url: '/mock/silver-craft.jpg',
    type: 'image',
    mime_type: 'image/jpeg',
    size: 1789012,
    dimensions: { width: 1400, height: 1050 },
    uploaded_by: 'Admin User',
    uploaded_at: new Date('2024-03-06T11:00:00'),
    alt_text: 'Kerajinan perak Kotagede',
    caption: 'Pengrajin perak sedang bekerja',
    used_in: ['UMKM', 'Kawasan'],
  },
  {
    id: '11',
    filename: 'ramayana-ballet-prambanan.jpg',
    url: '/mock/ramayana-ballet.jpg',
    type: 'image',
    mime_type: 'image/jpeg',
    size: 2890123,
    dimensions: { width: 2000, height: 1333 },
    uploaded_by: 'Editor User',
    uploaded_at: new Date('2024-03-05T20:00:00'),
    alt_text: 'Sendratari Ramayana di Prambanan',
    caption: 'Pertunjukan Ramayana Ballet',
    used_in: ['Agenda', 'Wisata'],
  },
  {
    id: '12',
    filename: 'alun-alun-kidul-night.jpg',
    url: '/mock/alunkidul-night.jpg',
    type: 'image',
    mime_type: 'image/jpeg',
    size: 1967890,
    dimensions: { width: 1500, height: 1000 },
    uploaded_by: 'Admin User',
    uploaded_at: new Date('2024-03-04T21:00:00'),
    alt_text: 'Alun-alun Kidul dengan becak hias',
    caption: 'Suasana malam di Alun-alun Kidul',
    used_in: ['Kawasan', 'Wisata', 'Galeri'],
  },
];
