import { Sejarah } from '../types';

export const mockSejarahData: Sejarah[] = [
  {
    id: '1',
    slug: 'filosofi-tata-ruang-keraton-yogyakarta',
    title_id: 'Filosofi Tata Ruang Keraton Yogyakarta: Manifestasi Kosmologi Jawa',
    title_en: 'Spatial Philosophy of Yogyakarta Palace: Manifestation of Javanese Cosmology',
    abstract_id:
      'Penelitian ini mengkaji filosofi tata ruang Keraton Yogyakarta sebagai manifestasi kosmologi Jawa. Tata ruang keraton mencerminkan konsep mikrokosmos-makrokosmos yang menghubungkan dunia manusia dengan alam semesta.',
    abstract_en:
      'This research examines the spatial philosophy of Yogyakarta Palace as a manifestation of Javanese cosmology. The palace layout reflects the microcosm-macrocosm concept that connects the human world with the universe.',
    content_id:
      'Keraton Yogyakarta dibangun dengan filosofi mendalam yang mencerminkan pandangan hidup masyarakat Jawa. Sumbu imajiner yang menghubungkan Laut Selatan, Keraton, Tugu Yogyakarta, dan Gunung Merapi bukan sekadar penataan geografis, melainkan representasi spiritual tentang keseimbangan antara dunia bawah (underworld), dunia tengah (manusia), dan dunia atas (spiritual).\n\nTata ruang dalam kompleks keraton mengikuti prinsip mancapat yang membagi ruang menjadi empat arah mata angin dengan pusat sebagai titik sakral. Setiap bangunan dan ruangan memiliki makna filosofis yang berkaitan dengan fungsi kosmologis dan sosialnya.\n\nPenelitian ini menggunakan metode etnografi dan analisis arsitektur untuk memahami bagaimana filosofi Jawa tertanam dalam setiap elemen fisik keraton.',
    content_en:
      'Yogyakarta Palace was built with a deep philosophy reflecting the Javanese worldview. The imaginary axis connecting the South Sea, the Palace, Tugu Yogyakarta, and Mount Merapi is not merely a geographical arrangement, but a spiritual representation of the balance between the underworld, the middle world (human), and the upper world (spiritual).\n\nThe layout within the palace complex follows the mancapat principle that divides space into four cardinal directions with the center as a sacred point. Each building and room has a philosophical meaning related to its cosmological and social function.\n\nThis research uses ethnographic methods and architectural analysis to understand how Javanese philosophy is embedded in every physical element of the palace.',
    category: 'Arsitektur',
    author: 'Dr. Soekarno Handoyo',
    author_affiliation: 'Universitas Gadjah Mada - Fakultas Ilmu Budaya',
    author_email: 'soekarno.h@ugm.ac.id',
    keywords_id: ['Keraton Yogyakarta', 'Kosmologi Jawa', 'Tata Ruang', 'Arsitektur Tradisional', 'Filosofi Mancapat'],
    keywords_en: ['Yogyakarta Palace', 'Javanese Cosmology', 'Spatial Planning', 'Traditional Architecture', 'Mancapat Philosophy'],
    images: ['/mock/research-keraton1.jpg', '/mock/research-keraton2.jpg'],
    featured_image: '/mock/research-keraton1.jpg',
    references: [
      'Atmojo, M. M. Sukarto K. (1992). Keraton Yogyakarta: Sejarah, Nasionalisme, dan Teladan Perjuangan. Jakarta: Rajawali Press.',
      'Santoso, J. (2008). Arsitektur-Kota Jawa: Kosmos, Kultur, dan Kuasa. Jakarta: Centropolis.',
    ],
    period: 'Abad 18 - Sekarang',
    related_locations: ['Keraton Yogyakarta', 'Tugu Yogyakarta', 'Alun-alun Kidul'],
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-15'),
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-02-20'),
    doi: '10.1234/sejarah.2024.001',
    citation_count: 23,
  },
  {
    id: '2',
    slug: 'peran-wanita-dalam-perjuangan-kemerdekaan-yogyakarta',
    title_id: 'Peran Perempuan dalam Perjuangan Kemerdekaan di Yogyakarta (1945-1949)',
    title_en: "Women's Role in the Independence Struggle in Yogyakarta (1945-1949)",
    abstract_id:
      'Studi ini mengungkap peran penting perempuan dalam perjuangan kemerdekaan Indonesia di Yogyakarta periode 1945-1949, yang selama ini kurang mendapat perhatian dalam historiografi nasional.',
    abstract_en:
      "This study reveals the important role of women in Indonesia's independence struggle in Yogyakarta during 1945-1949, which has received less attention in national historiography.",
    content_id:
      'Ketika Yogyakarta menjadi ibukota Republik Indonesia (1946-1949), perempuan memainkan peran vital dalam berbagai aspek perjuangan. Tidak hanya sebagai pendukung di belakang layar, mereka aktif dalam diplomasi, perlawanan bersenjata, dan mempertahankan kesejahteraan masyarakat.\n\nOrganisasi seperti Wanita Utama, Barisan Pelopor Wanita, dan Palang Merah Indonesia dipimpin oleh tokoh-tokoh seperti S.K. Trimurti dan Maria Ulfah Santoso. Mereka mengorganisir dapur umum, layanan kesehatan, dan bahkan menyelundupkan senjata dan dokumen penting.\n\nDokumentasi dari arsip Monumen Jogja Kembali dan wawancara dengan keluarga pejuang menunjukkan bahwa kontribusi perempuan sangat signifikan namun sering diabaikan dalam narasi sejarah resmi.',
    content_en:
      'When Yogyakarta became the capital of the Republic of Indonesia (1946-1949), women played a vital role in various aspects of the struggle. Not only as supporters behind the scenes, they were active in diplomacy, armed resistance, and maintaining community welfare.\n\nOrganizations such as Wanita Utama, Barisan Pelopor Wanita, and the Indonesian Red Cross were led by figures such as S.K. Trimurti and Maria Ulfah Santoso. They organized soup kitchens, health services, and even smuggled weapons and important documents.\n\nDocumentation from the Jogja Kembali Monument archives and interviews with families of fighters show that women\'s contributions were very significant but often overlooked in official historical narratives.',
    category: 'Sejarah',
    author: 'Prof. Dr. Retno Winarni',
    author_affiliation: 'Universitas Negeri Yogyakarta - Fakultas Ilmu Sosial',
    author_email: 'retno.w@uny.ac.id',
    keywords_id: ['Perempuan', 'Perjuangan Kemerdekaan', 'Yogyakarta', 'Ibukota RI', 'S.K. Trimurti'],
    keywords_en: ['Women', 'Independence Struggle', 'Yogyakarta', 'Capital of Indonesia', 'S.K. Trimurti'],
    images: ['/mock/research-women1.jpg'],
    featured_image: '/mock/research-women1.jpg',
    references: [
      'Frederick, William H. (1989). Visions and Heat: The Making of the Indonesian Revolution. Ohio University Press.',
      'Locher-Scholten, E. (2000). Women and the Colonial State. Amsterdam University Press.',
    ],
    period: '1945-1949',
    related_locations: ['Yogyakarta', 'Monumen Jogja Kembali', 'Benteng Vredeburg'],
    featured: true,
    status: 'published',
    published_at: new Date('2024-02-01'),
    created_at: new Date('2024-01-25'),
    updated_at: new Date('2024-02-15'),
    doi: '10.1234/sejarah.2024.002',
    citation_count: 18,
  },
  {
    id: '3',
    slug: 'makna-simbolis-motif-batik-yogyakarta',
    title_id: 'Makna Simbolis Motif Batik Yogyakarta: Kajian Semiotika dan Antropologi',
    title_en: 'Symbolic Meaning of Yogyakarta Batik Motifs: Semiotic and Anthropological Study',
    abstract_id:
      'Penelitian ini menganalisis makna simbolis motif batik khas Yogyakarta menggunakan pendekatan semiotika dan antropologi. Setiap motif mengandung filosofi hidup dan nilai-nilai budaya Jawa.',
    abstract_en:
      'This research analyzes the symbolic meaning of Yogyakarta batik motifs using semiotic and anthropological approaches. Each motif contains life philosophy and Javanese cultural values.',
    content_id:
      'Batik Yogyakarta memiliki karakteristik unik dengan motif-motif klasik seperti Parang, Kawung, Semen, dan Truntum. Setiap motif bukan sekadar ornamen estetis, melainkan membawa pesan filosofis mendalam tentang kehidupan, kekuasaan, dan spiritualitas.\n\nMotif Parang Rusak, misalnya, secara historis hanya boleh dikenakan oleh Sultan dan keluarga keraton. Bentuk diagonal yang tegas melambangkan kekuatan, kepemimpinan, dan ketegasan dalam menghadapi tantangan.\n\nPenelitian lapangan dilakukan dengan mewawancarai pembatik turun-temurun di Kampung Batik Kauman dan mengkaji koleksi batik di Museum Batik Yogyakarta. Analisis semiotika Pierce digunakan untuk membedah makna ikon, indeks, dan simbol dalam setiap motif.',
    content_en:
      'Yogyakarta batik has unique characteristics with classic motifs such as Parang, Kawung, Semen, and Truntum. Each motif is not merely an aesthetic ornament, but carries deep philosophical messages about life, power, and spirituality.\n\nThe Parang Rusak motif, for example, could historically only be worn by the Sultan and royal family. The firm diagonal shape symbolizes strength, leadership, and assertiveness in facing challenges.\n\nField research was conducted by interviewing hereditary batik makers in Kampung Batik Kauman and examining batik collections at the Yogyakarta Batik Museum. Pierce\'s semiotic analysis is used to dissect the meaning of icons, indexes, and symbols in each motif.',
    category: 'Seni',
    author: 'Dr. Ayu Kusumawati',
    author_affiliation: 'Institut Seni Indonesia Yogyakarta',
    author_email: 'ayu.kusuma@isi.ac.id',
    keywords_id: ['Batik Yogyakarta', 'Motif Batik', 'Semiotika', 'Antropologi', 'Parang Rusak'],
    keywords_en: ['Yogyakarta Batik', 'Batik Motif', 'Semiotics', 'Anthropology', 'Parang Rusak'],
    images: ['/mock/research-batik1.jpg', '/mock/research-batik2.jpg', '/mock/research-batik3.jpg'],
    featured_image: '/mock/research-batik1.jpg',
    references: [
      'Djoemena, Nian S. (1990). Ungkapan Sehelai Batik: Its Mystery and Meaning. Jakarta: Djambatan.',
      'Santosa, R. (2013). Semiotika Sosial: Pandangan terhadap Bahasa. Surabaya: Pustaka Eureka.',
    ],
    period: 'Abad 18 - Sekarang',
    related_locations: ['Kampung Batik Kauman', 'Museum Batik Yogyakarta', 'Keraton Yogyakarta'],
    featured: true,
    status: 'published',
    published_at: new Date('2024-02-10'),
    created_at: new Date('2024-02-05'),
    updated_at: new Date('2024-02-25'),
    doi: '10.1234/sejarah.2024.003',
    citation_count: 31,
  },
  {
    id: '4',
    slug: 'tradisi-lisan-mitos-nyi-roro-kidul',
    title_id: 'Tradisi Lisan dan Mitos Nyi Roro Kidul dalam Budaya Pesisir Selatan Yogyakarta',
    title_en: 'Oral Tradition and the Myth of Nyi Roro Kidul in the South Coast Culture of Yogyakarta',
    abstract_id:
      'Kajian antropologi tentang mitos Nyi Roro Kidul yang masih hidup dalam masyarakat pesisir selatan Yogyakarta dan pengaruhnya terhadap praktik budaya sehari-hari.',
    abstract_en:
      'Anthropological study of the Nyi Roro Kidul myth still alive in the south coast community of Yogyakarta and its influence on daily cultural practices.',
    content_id:
      'Mitos Nyi Roro Kidul, penguasa Laut Selatan, bukan sekadar dongeng melainkan bagian integral dari sistem kepercayaan masyarakat pesisir Yogyakarta. Kepercayaan ini mempengaruhi berbagai aspek kehidupan, mulai dari larangan mengenakan pakaian hijau di pantai hingga upacara ritual Labuhan yang diadakan Sultan setiap tahun.\n\nPenelitian etnografi selama 12 bulan di kawasan Parangtritis, Parangkusumo, dan Glagah menunjukkan bahwa mitos ini berfungsi sebagai mekanisme kontrol sosial dan pelestarian lingkungan. Nelayan tradisional menggunakan kepercayaan ini sebagai pedoman dalam menangkap ikan dan menjaga kelestarian laut.\n\nWawancara dengan tokoh spiritual lokal (dukun pantai) mengungkap bahwa mitos Nyi Roro Kidul beradaptasi dengan modernitas tanpa kehilangan esensi spiritualnya.',
    content_en:
      'The myth of Nyi Roro Kidul, ruler of the South Sea, is not just a fairy tale but an integral part of the belief system of the coastal community of Yogyakarta. This belief influences various aspects of life, from the prohibition of wearing green clothes on the beach to the Labuhan ritual ceremony held by the Sultan every year.\n\nEthnographic research over 12 months in the Parangtritis, Parangkusumo, and Glagah areas shows that this myth functions as a mechanism of social control and environmental preservation. Traditional fishermen use this belief as a guide in fishing and maintaining marine conservation.\n\nInterviews with local spiritual figures (beach shamans) reveal that the myth of Nyi Roro Kidul adapts to modernity without losing its spiritual essence.',
    category: 'Antropologi',
    author: 'Dr. Bambang Sutrisno, M.A.',
    author_affiliation: 'Universitas Gadjah Mada - Fakultas Ilmu Budaya',
    author_email: 'bambang.sutrisno@ugm.ac.id',
    keywords_id: ['Nyi Roro Kidul', 'Tradisi Lisan', 'Mitos', 'Pesisir Selatan', 'Ritual Labuhan'],
    keywords_en: ['Nyi Roro Kidul', 'Oral Tradition', 'Myth', 'South Coast', 'Labuhan Ritual'],
    images: ['/mock/research-pantai1.jpg', '/mock/research-pantai2.jpg'],
    featured_image: '/mock/research-pantai1.jpg',
    references: [
      'Geertz, Clifford. (1960). The Religion of Java. Chicago: University of Chicago Press.',
      'Woodward, Mark. (1989). Islam in Java: Normative Piety and Mysticism. Tucson: University of Arizona Press.',
    ],
    period: 'Abad 16 - Sekarang',
    related_locations: ['Pantai Parangtritis', 'Parangkusumo', 'Keraton Yogyakarta'],
    featured: false,
    status: 'published',
    published_at: new Date('2024-02-20'),
    created_at: new Date('2024-02-15'),
    updated_at: new Date('2024-03-01'),
    doi: '10.1234/sejarah.2024.004',
    citation_count: 15,
  },
  {
    id: '5',
    slug: 'evolusi-arsitektur-masjid-kotagede',
    title_id: 'Evolusi Arsitektur Masjid Agung Kotagede: Perpaduan Islam dan Tradisi Jawa',
    title_en: 'Architectural Evolution of Kotagede Grand Mosque: Fusion of Islam and Javanese Tradition',
    abstract_id:
      'Penelitian ini menelusuri evolusi arsitektur Masjid Agung Kotagede sejak abad ke-16 hingga renovasi modern, menunjukkan akulturasi Islam dan budaya Jawa.',
    abstract_en:
      'This research traces the architectural evolution of Kotagede Grand Mosque from the 16th century to modern renovation, showing the acculturation of Islam and Javanese culture.',
    content_id:
      'Masjid Agung Kotagede, yang didirikan pada masa Kerajaan Mataram Islam, merupakan contoh sempurna akulturasi arsitektur Islam dengan tradisi Jawa. Struktur atap tumpang yang khas arsitektur candi Hindu-Buddha dipadukan dengan fungsi masjid Islam.\n\nPengukuran arsitektural dan studi dokumen historis menunjukkan bahwa masjid ini mengalami beberapa fase renovasi, namun tetap mempertahankan karakter aslinya. Mihrab, mimbar, dan serambi menunjukkan pengaruh Timur Tengah yang diinterpretasi ulang dengan estetika Jawa.\n\nPenelitian ini juga menganalisis makam para pendiri Mataram di kompleks masjid, yang menjadi bukti pentingnya tempat ini dalam sejarah Jawa Islam.',
    content_en:
      'Kotagede Grand Mosque, founded during the Islamic Mataram Kingdom, is a perfect example of the acculturation of Islamic architecture with Javanese tradition. The typical tiered roof structure of Hindu-Buddhist temple architecture is combined with Islamic mosque functions.\n\nArchitectural measurements and historical document studies show that this mosque has undergone several phases of renovation, but still maintains its original character. The mihrab, pulpit, and terrace show Middle Eastern influences reinterpreted with Javanese aesthetics.\n\nThis research also analyzes the tombs of the founders of Mataram in the mosque complex, which are evidence of the importance of this place in the history of Javanese Islam.',
    category: 'Arsitektur',
    author: 'Prof. Dr. Ir. Revianto Budi Santoso',
    author_affiliation: 'Universitas Islam Indonesia - Fakultas Teknik Sipil dan Perencanaan',
    author_email: 'revianto.budi@uii.ac.id',
    keywords_id: ['Masjid Kotagede', 'Arsitektur Islam-Jawa', 'Mataram Islam', 'Akulturasi', 'Arsitektur Masjid'],
    keywords_en: ['Kotagede Mosque', 'Islamic-Javanese Architecture', 'Islamic Mataram', 'Acculturation', 'Mosque Architecture'],
    images: ['/mock/research-masjid1.jpg', '/mock/research-masjid2.jpg'],
    featured_image: '/mock/research-masjid1.jpg',
    references: [
      'Tjandrasasmita, Uka. (2009). Arkeologi Islam Nusantara. Jakarta: KPG.',
      'Grabar, Oleg. (1988). The Formation of Islamic Art. Yale University Press.',
    ],
    period: 'Abad 16 - Sekarang',
    related_locations: ['Masjid Agung Kotagede', 'Makam Raja-raja Mataram', 'Kotagede'],
    featured: false,
    status: 'published',
    published_at: new Date('2024-03-01'),
    created_at: new Date('2024-02-25'),
    updated_at: new Date('2024-03-05'),
    doi: '10.1234/sejarah.2024.005',
    citation_count: 12,
  },
  {
    id: '6',
    slug: 'sistem-ekonomi-tradisional-pasar-beringharjo',
    title_id: 'Sistem Ekonomi Tradisional Pasar Beringharjo: Kontinuitas dan Perubahan',
    title_en: 'Traditional Economic System of Beringharjo Market: Continuity and Change',
    abstract_id:
      'Studi etnoekonomi tentang Pasar Beringharjo yang telah beroperasi sejak 1758, menganalisis bagaimana pasar tradisional bertahan di era modern.',
    abstract_en:
      'Ethno-economic study of Beringharjo Market operating since 1758, analyzing how traditional markets survive in the modern era.',
    content_id:
      'Pasar Beringharjo, yang didirikan oleh Sultan Hamengku Buwono I, merupakan pusat ekonomi tradisional Yogyakarta yang masih bertahan hingga kini. Penelitian ini menggunakan metode etnografi ekonomi untuk memahami sistem perdagangan, jaringan sosial pedagang, dan adaptasi terhadap perubahan ekonomi modern.\n\nDitemukan bahwa keberlangsungan pasar ini bukan hanya karena lokasi strategis, tetapi juga karena sistem kepercayaan (trust system) antar pedagang dan pembeli yang diwariskan turun-temurun. Konsep "langganan" menciptakan loyalitas pelanggan yang tidak bisa ditiru oleh sistem retail modern.\n\nPenelitian juga mengungkap bagaimana pedagang Beringharjo beradaptasi dengan era digital melalui WhatsApp dan media sosial tanpa meninggalkan nilai-nilai tradisional.',
    content_en:
      'Beringharjo Market, founded by Sultan Hamengku Buwono I, is a traditional economic center of Yogyakarta that still survives today. This research uses economic ethnography methods to understand the trading system, social networks of traders, and adaptation to modern economic changes.\n\nIt was found that the sustainability of this market is not only due to its strategic location, but also due to the trust system between traders and buyers that has been passed down through generations. The concept of "langganan" creates customer loyalty that cannot be replicated by modern retail systems.\n\nThe research also reveals how Beringharjo traders adapt to the digital era through WhatsApp and social media without abandoning traditional values.',
    category: 'Antropologi',
    author: 'Dr. Rina Herlina Haryanti, S.E., M.Si.',
    author_affiliation: 'Universitas Pembangunan Nasional Veteran Yogyakarta',
    author_email: 'rina.herlina@upnyk.ac.id',
    keywords_id: ['Pasar Beringharjo', 'Ekonomi Tradisional', 'Etnoekonomi', 'Sistem Langganan', 'Adaptasi Digital'],
    keywords_en: ['Beringharjo Market', 'Traditional Economy', 'Ethno-economics', 'Subscription System', 'Digital Adaptation'],
    images: ['/mock/research-pasar1.jpg'],
    featured_image: '/mock/research-pasar1.jpg',
    references: [
      'Geertz, Clifford. (1963). Peddlers and Princes: Social Change and Economic Modernization. Chicago: University of Chicago Press.',
      'Scott, James C. (1976). The Moral Economy of the Peasant. Yale University Press.',
    ],
    period: '1758 - Sekarang',
    related_locations: ['Pasar Beringharjo', 'Malioboro', 'Keraton Yogyakarta'],
    featured: false,
    status: 'draft',
    created_at: new Date('2024-03-10'),
    updated_at: new Date('2024-03-12'),
  },
];
