import { UMKM } from '../types';

export const mockUMKMData: UMKM[] = [
  {
    id: '1',
    slug: 'batik-winotosastro',
    business_name: 'Batik Winotosastro',
    owner_name: 'Ibu Siti Nurjanah',
    category: 'Batik & Tekstil',
    description_id: 'Pengrajin batik tulis tradisional dengan motif klasik Yogyakarta. Menyediakan batik cap dan tulis berkualitas tinggi dengan pewarna alami.',
    description_en: 'Traditional hand-drawn batik artisan with classic Yogyakarta motifs. Provides high-quality stamped and hand-drawn batik with natural dyes.',
    products: [
      {
        name_id: 'Kain Batik Tulis',
        name_en: 'Hand-drawn Batik Cloth',
        price_range: 'Rp 500.000 - Rp 2.000.000',
        description_id: 'Kain batik tulis premium dengan motif parang dan kawung',
        description_en: 'Premium hand-drawn batik cloth with parang and kawung motifs',
      },
      {
        name_id: 'Kemeja Batik',
        name_en: 'Batik Shirt',
        price_range: 'Rp 250.000 - Rp 800.000',
      },
      {
        name_id: 'Kain Jarik',
        name_en: 'Jarik Cloth',
        price_range: 'Rp 150.000 - Rp 500.000',
      },
    ],
    products_id: ['Batik Tulis', 'Batik Cap', 'Kain Jarik', 'Kemeja Batik'],
    products_en: ['Hand-drawn Batik', 'Stamped Batik', 'Jarik Cloth', 'Batik Shirts'],
    price_range_id: 'Rp 150.000 - Rp 2.500.000',
    price_range_en: 'Rp 150,000 - Rp 2,500,000',
    images: ['/mock/batik1.jpg', '/mock/batik2.jpg', '/mock/batik3.jpg'],
    featured_image: '/mock/batik1.jpg',
    contact: {
      phone: '081234567890',
      whatsapp: '081234567890',
      email: 'batiksogan@gmail.com',
    },
    location: {
      address: 'Jl. Tirtodipuran No. 45, Mantrijeron, Yogyakarta',
      coordinates: { lat: -7.8145, lng: 110.3659 },
    },
    location_id: 'Kawasan Keraton',
    location_en: 'Palace Area',
    social_media: {
      instagram: '@batikwinotosastro',
      facebook: 'batikwinotosastro',
    },
    operating_hours: {
      open_time: '08:00',
      close_time: '17:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    status: 'published',
    featured: true,
    verified: true,
    published_at: new Date('2024-01-15'),
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-01-20'),
  },
  {
    id: '2',
    slug: 'kerajinan-wayang-pak-joko',
    business_name: 'Kerajinan Wayang Pak Joko',
    owner_name: 'Pak Joko Suwarno',
    category: 'Kerajinan',
    description_id: 'Pembuat wayang kulit tradisional dengan detail rumit. Setiap wayang dibuat dengan teknik ukir dan sungging yang autentik.',
    description_en: 'Handcrafted shadow puppets made by experienced craftsmen. Each puppet is meticulously carved with high artistic value.',
    products: [
      {
        name_id: 'Wayang Kulit',
        name_en: 'Shadow Puppets',
        price_range: 'Rp 1.500.000 - Rp 5.000.000',
      },
      {
        name_id: 'Miniatur Wayang',
        name_en: 'Miniature Puppets',
        price_range: 'Rp 150.000 - Rp 500.000',
      },
      {
        name_id: 'Gunungan',
        name_en: 'Gunungan',
        price_range: 'Rp 500.000 - Rp 2.000.000',
      },
    ],
    products_id: ['Wayang Kulit', 'Wayang Golek', 'Miniatur Wayang', 'Gunungan'],
    products_en: ['Shadow Puppets', 'Miniature Puppets', 'Puppet Accessories', 'Customized Puppets'],
    price_range_id: 'Rp 200.000 - Rp 5.000.000',
    price_range_en: 'Rp 250,000 - Rp 5,000,000',
    images: ['/mock/wayang1.jpg', '/mock/wayang2.jpg'],
    featured_image: '/mock/wayang1.jpg',
    contact: {
      phone: '081345678901',
      email: 'wayangkulit.joko@gmail.com',
    },
    location: {
      address: 'Kampung Dagen, Patehan, Kraton, Yogyakarta',
    },
    location_id: 'Kawasan Keraton',
    location_en: 'Palace Area',
    social_media: {
      instagram: '@wayangpakjoko',
      facebook: 'wayangpakjoko',
    },
    status: 'published',
    featured: true,
    verified: true,
    published_at: new Date('2024-02-01'),
    created_at: new Date('2024-01-25'),
    updated_at: new Date('2024-02-05'),
  },
  {
    id: '3',
    slug: 'gudeg-yu-djum',
    business_name: 'Gudeg Yu Djum',
    owner_name: 'Ibu Djumilah',
    category: 'Kuliner',
    description_id: 'Warung gudeg legendaris dengan resep turun temurun. Menyajikan gudeg khas Yogyakarta dengan cita rasa manis yang khas.',
    description_en: 'Legendary authentic Yogyakarta gudeg with recipes passed down through generations. Sweet, savory, and tender flavors in every bite.',
    products: [
      {
        name_id: 'Paket Gudeg Komplit',
        name_en: 'Complete Gudeg Package',
        price_range: 'Rp 25.000 - Rp 50.000',
        description_id: 'Gudeg, ayam, telur, krecek, dan sambal goreng',
        description_en: 'Gudeg, chicken, egg, krecek, and sambal goreng',
      },
      {
        name_id: 'Gudeg Kaleng',
        name_en: 'Canned Gudeg',
        price_range: 'Rp 35.000',
      },
    ],
    products_id: ['Gudeg Kering', 'Gudeg Basah', 'Ayam Kampung', 'Telur Pindang'],
    products_en: ['Dry Gudeg', 'Wet Gudeg', 'Packaged Gudeg', 'Complete Gudeg Set'],
    price_range_id: 'Rp 15.000 - Rp 35.000',
    price_range_en: 'Rp 15,000 - Rp 100,000',
    images: ['/mock/gudeg1.jpg', '/mock/gudeg2.jpg'],
    featured_image: '/mock/gudeg1.jpg',
    contact: {
      phone: '0274123456',
      whatsapp: '081298765432',
      email: 'info@gudegyudjum.com',
    },
    location: {
      address: 'Jl. Wijilan No. 31, Yogyakarta',
      coordinates: { lat: -7.8034, lng: 110.3656 },
    },
    location_id: 'Kawasan Malioboro',
    location_en: 'Malioboro Area',
    social_media: {
      instagram: '@gudegyudjum',
      facebook: 'gudegyudjum',
    },
    operating_hours: {
      open_time: '06:00',
      close_time: '22:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    status: 'published',
    featured: true,
    verified: true,
    published_at: new Date('2024-01-12'),
    created_at: new Date('2024-01-08'),
    updated_at: new Date('2024-01-18'),
  },
  {
    id: '4',
    slug: 'silver-kotagede',
    business_name: 'Silver Kotagede',
    owner_name: 'Pak Bambang Riyanto',
    category: 'Perhiasan & Aksesoris',
    description_id: 'Pengrajin perak dengan teknik tatah dan ukir tradisional. Produk perhiasan dan souvenir perak berkualitas ekspor.',
    description_en: 'Fine silver craftsmen from the historic Kotagede area. Creates jewelry and accessories with intricate details and guaranteed quality.',
    products: [
      {
        name_id: 'Cincin Perak',
        name_en: 'Silver Ring',
        price_range: 'Rp 150.000 - Rp 1.000.000',
      },
      {
        name_id: 'Gelang Perak',
        name_en: 'Silver Bracelet',
        price_range: 'Rp 200.000 - Rp 800.000',
      },
      {
        name_id: 'Miniatur Perak',
        name_en: 'Silver Miniature',
        price_range: 'Rp 500.000 - Rp 3.000.000',
      },
    ],
    products_id: ['Cincin Perak', 'Gelang', 'Liontin', 'Miniatur Perak'],
    products_en: ['Silver Jewelry', 'Silver Brooches', 'Silver Accessories', 'Custom Silver'],
    price_range_id: 'Rp 100.000 - Rp 3.000.000',
    price_range_en: 'Rp 200,000 - Rp 3,000,000',
    images: ['/mock/silver1.jpg', '/mock/silver2.jpg'],
    featured_image: '/mock/silver1.jpg',
    contact: {
      phone: '0274377777',
      whatsapp: '085678901234',
      email: 'info@silverkotagede.com',
    },
    location: {
      address: 'Jl. Mondorakan, Kotagede, Yogyakarta',
      coordinates: { lat: -7.8275, lng: 110.3987 },
    },
    location_id: 'Kawasan Kota Gede',
    location_en: 'Kota Gede Area',
    social_media: {
      instagram: '@silverkotagede',
      facebook: 'silverkotagede',
    },
    operating_hours: {
      open_time: '09:00',
      close_time: '17:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    status: 'published',
    featured: true,
    verified: true,
    published_at: new Date('2024-02-05'),
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2024-02-12'),
  },
  {
    id: '5',
    slug: 'gerabah-kasongan',
    business_name: 'Gerabah Kasongan',
    owner_name: 'Pak Suroto',
    category: 'Kerajinan',
    description_id: 'Sentra kerajinan gerabah dan keramik dengan berbagai bentuk dan ukuran. Dari peralatan dapur hingga dekorasi rumah.',
    description_en: 'Handcrafted ceramics from Kasongan Village, famous for creative ceramic products. Perfect for home decoration and souvenirs.',
    products: [
      {
        name_id: 'Vas Bunga',
        name_en: 'Decorative Vases',
        price_range: 'Rp 50.000 - Rp 300.000',
      },
      {
        name_id: 'Guci',
        name_en: 'Clay Pots',
        price_range: 'Rp 100.000 - Rp 500.000',
      },
      {
        name_id: 'Patung Tanah Liat',
        name_en: 'Statues',
        price_range: 'Rp 75.000 - Rp 400.000',
      },
    ],
    products_id: ['Vas Bunga', 'Guci', 'Piring Keramik', 'Patung Tanah Liat'],
    products_en: ['Decorative Vases', 'Clay Pots', 'Statues', 'Utensils'],
    price_range_id: 'Rp 25.000 - Rp 500.000',
    price_range_en: 'Rp 25,000 - Rp 500,000',
    images: ['/mock/gerabah1.jpg', '/mock/gerabah2.jpg'],
    featured_image: '/mock/gerabah1.jpg',
    contact: {
      phone: '081567890123',
      email: 'info@gerabahkasongan.com',
    },
    location: {
      address: 'Kasongan, Bangunjiwo, Kasihan, Bantul',
      coordinates: { lat: -7.8483, lng: 110.3411 },
    },
    location_id: 'Kawasan Kota Gede',
    location_en: 'Kota Gede Area',
    social_media: {
      instagram: '@gerabahkasongan',
      facebook: 'gerabahkasongan',
    },
    operating_hours: {
      open_time: '08:00',
      close_time: '17:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    status: 'published',
    featured: true,
    verified: true,
    published_at: new Date('2024-02-08'),
    created_at: new Date('2024-02-05'),
    updated_at: new Date('2024-02-15'),
  },
  {
    id: '6',
    slug: 'bakpia-pathok-25',
    business_name: 'Bakpia Pathok 25',
    owner_name: 'Bapak Sutarno',
    category: 'Kuliner',
    description_id: 'Produsen bakpia legendaris dengan berbagai varian rasa. Oleh-oleh khas Yogyakarta yang wajib dibawa pulang.',
    description_en: 'Legendary Bakpia Pathok with various flavors. The most popular souvenir from Yogyakarta with authentic taste and guaranteed quality.',
    products: [
      {
        name_id: 'Bakpia Kacang Hijau',
        name_en: 'Mung Bean Bakpia',
        price_range: 'Rp 50.000/box',
      },
      {
        name_id: 'Bakpia Coklat',
        name_en: 'Chocolate Bakpia',
        price_range: 'Rp 55.000/box',
      },
      {
        name_id: 'Bakpia Keju',
        name_en: 'Cheese Bakpia',
        price_range: 'Rp 60.000/box',
      },
    ],
    products_id: ['Bakpia Kacang Hijau', 'Bakpia Coklat', 'Bakpia Keju', 'Bakpia Kumbu'],
    products_en: ['Mung Bean Bakpia', 'Chocolate Bakpia', 'Cheese Bakpia', 'Durian Bakpia'],
    price_range_id: 'Rp 35.000 - Rp 75.000',
    price_range_en: 'Rp 35,000 - Rp 80,000',
    images: ['/mock/bakpia1.jpg'],
    featured_image: '/mock/bakpia1.jpg',
    contact: {
      phone: '0274588888',
      whatsapp: '081234999888',
      email: 'bakpiapathok25@gmail.com',
    },
    location: {
      address: 'Jl. KH. Ali Maksum, Krapyak, Yogyakarta',
    },
    location_id: 'Kawasan Malioboro',
    location_en: 'Malioboro Area',
    social_media: {
      instagram: '@bakpiapathok25',
      facebook: 'bakpiapathok25',
      website: 'https://bakpiapathok25.com',
    },
    operating_hours: {
      open_time: '08:00',
      close_time: '21:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    status: 'published',
    featured: true,
    verified: true,
    published_at: new Date('2024-01-20'),
    created_at: new Date('2024-01-15'),
    updated_at: new Date('2024-02-10'),
  },
  {
    id: '7',
    slug: 'angkringan-lik-man',
    business_name: 'Angkringan Lik Man',
    owner_name: 'Lik Man',
    category: 'Kuliner',
    description_id: 'Angkringan legendaris di Tugu Yogyakarta. Menu favorit mahasiswa dan wisatawan dengan harga terjangkau.',
    description_en: 'Legendary angkringan at Tugu Yogyakarta. Favorite menu of students and tourists with affordable prices.',
    products: [
      {
        name_id: 'Nasi Kucing',
        name_en: 'Cat Rice',
        price_range: 'Rp 3.000',
      },
      {
        name_id: 'Sate Usus',
        name_en: 'Intestine Satay',
        price_range: 'Rp 2.000',
      },
      {
        name_id: 'Wedang Jahe',
        name_en: 'Ginger Drink',
        price_range: 'Rp 5.000',
      },
    ],
    products_id: ['Nasi Kucing', 'Sate Usus', 'Sate Telur', 'Wedang Jahe'],
    products_en: ['Cat Rice', 'Intestine Satay', 'Egg Satay', 'Ginger Drink'],
    price_range_id: 'Rp 2.000 - Rp 10.000',
    price_range_en: 'Rp 2,000 - Rp 10,000',
    images: ['/mock/angkringan1.jpg'],
    featured_image: '/mock/angkringan1.jpg',
    contact: {
      phone: '081390123456',
    },
    location: {
      address: 'Jl. Jend. Sudirman (dekat Tugu), Yogyakarta',
      coordinates: { lat: -7.7830, lng: 110.3669 },
    },
    location_id: 'Kawasan Tugu',
    location_en: 'Tugu Area',
    social_media: {},
    operating_hours: {
      open_time: '18:00',
      close_time: '02:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    status: 'published',
    featured: true,
    verified: true,
    published_at: new Date('2024-01-25'),
    created_at: new Date('2024-01-20'),
    updated_at: new Date('2024-02-08'),
  },
  {
    id: '8',
    slug: 'lurik-sutra-ibu-siti',
    business_name: 'Lurik Sutra Ibu Siti',
    owner_name: 'Ibu Siti Aminah',
    category: 'Fashion',
    description_id: 'Tenun lurik kombinasi sutra dengan motif tradisional. Tersedia kain dan produk jadi seperti tas dan dompet.',
    description_en: 'Lurik weaving combined with silk in traditional motifs. Available fabric and finished products like bags and wallets.',
    products: [
      {
        name_id: 'Kain Lurik Sutra',
        name_en: 'Silk Lurik Fabric',
        price_range: 'Rp 300.000 - Rp 800.000',
      },
      {
        name_id: 'Tas Lurik',
        name_en: 'Lurik Bag',
        price_range: 'Rp 150.000 - Rp 400.000',
      },
    ],
    products_id: ['Kain Lurik Sutra', 'Tas Lurik', 'Dompet Lurik', 'Selendang'],
    products_en: ['Silk Lurik Fabric', 'Lurik Bag', 'Lurik Wallet', 'Shawl'],
    price_range_id: 'Rp 150.000 - Rp 800.000',
    price_range_en: 'Rp 150,000 - Rp 800,000',
    images: ['/mock/lurik1.jpg'],
    featured_image: '/mock/lurik1.jpg',
    contact: {
      phone: '085712345678',
      whatsapp: '085712345678',
    },
    location: {
      address: 'Imogiri, Bantul, Yogyakarta',
    },
    location_id: 'Kawasan Imogiri',
    location_en: 'Imogiri Area',
    social_media: {
      instagram: '@luriksutra_siti',
    },
    status: 'published',
    featured: false,
    verified: true,
    published_at: new Date('2024-02-10'),
    created_at: new Date('2024-02-05'),
    updated_at: new Date('2024-02-11'),
  },
];
