import { UMKM } from '../types';

export const mockUMKMData: UMKM[] = [
  {
    id: '1',
    slug: 'batik-sogan-heritage',
    business_name: 'Batik Sogan Heritage',
    owner_name: 'Ibu Siti Nurjanah',
    category: 'Kerajinan',
    description_id: 'Pengrajin batik tulis tradisional dengan motif khas Yogyakarta. Menggunakan pewarna alami dari bahan tumbuhan.',
    description_en: 'Traditional hand-drawn batik craftsman with distinctive Yogyakarta motifs. Using natural dyes from plant materials.',
    products: [
      {
        name_id: 'Kain Batik Tulis',
        name_en: 'Hand-drawn Batik Cloth',
        price_range: 'Rp 500.000 - Rp 2.000.000',
        description_id: 'Kain batik tulis premium dengan motif parang dan kawung',
        description_en: 'Premium hand-drawn batik cloth with parang and kawung motifs',
      },
      {
        name_id: 'Kemeja Batik',
        name_en: 'Batik Shirt',
        price_range: 'Rp 250.000 - Rp 800.000',
      },
    ],
    images: ['/mock/batik1.jpg', '/mock/batik2.jpg', '/mock/batik3.jpg'],
    featured_image: '/mock/batik1.jpg',
    contact: {
      phone: '081234567890',
      whatsapp: '081234567890',
      email: 'batiksogan@gmail.com',
    },
    location: {
      address: 'Jl. Tirtodipuran No. 45, Mantrijeron, Yogyakarta',
      coordinates: { lat: -7.8145, lng: 110.3659 },
    },
    social_media: {
      instagram: '@batiksogan_heritage',
      facebook: 'BatikSoganHeritage',
    },
    operating_hours: {
      open_time: '08:00',
      close_time: '17:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    status: 'published',
    featured: true,
    verified: true,
    published_at: new Date('2024-01-15'),
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-01-20'),
  },
  {
    id: '2',
    slug: 'gudeg-yu-djum',
    business_name: 'Gudeg Yu Djum',
    owner_name: 'Ibu Djumilah',
    category: 'Kuliner',
    description_id: 'Gudeg legendaris Yogyakarta yang sudah berdiri sejak 1950-an. Terkenal dengan rasa manis khas dan telur bacem yang lezat.',
    description_en: 'Legendary Yogyakarta gudeg established since the 1950s. Famous for its distinctive sweet taste and delicious bacem eggs.',
    products: [
      {
        name_id: 'Paket Gudeg Komplit',
        name_en: 'Complete Gudeg Package',
        price_range: 'Rp 25.000 - Rp 50.000',
        description_id: 'Gudeg, ayam, telur, krecek, dan sambal goreng',
        description_en: 'Gudeg, chicken, egg, krecek, and sambal goreng',
      },
      {
        name_id: 'Gudeg Kaleng',
        name_en: 'Canned Gudeg',
        price_range: 'Rp 35.000',
      },
    ],
    images: ['/mock/gudeg1.jpg', '/mock/gudeg2.jpg'],
    featured_image: '/mock/gudeg1.jpg',
    contact: {
      phone: '0274123456',
      whatsapp: '081298765432',
    },
    location: {
      address: 'Jl. Wijilan No. 31, Yogyakarta',
      coordinates: { lat: -7.8034, lng: 110.3656 },
    },
    social_media: {
      instagram: '@gudegyudjum_official',
    },
    operating_hours: {
      open_time: '06:00',
      close_time: '22:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    status: 'published',
    featured: true,
    verified: true,
    published_at: new Date('2024-01-12'),
    created_at: new Date('2024-01-08'),
    updated_at: new Date('2024-01-18'),
  },
  {
    id: '3',
    slug: 'kerajinan-wayang-kulit',
    business_name: 'Kerajinan Wayang Kulit Pak Hadi',
    owner_name: 'Pak Hadi Suwarno',
    category: 'Kerajinan',
    description_id: 'Pembuat wayang kulit tradisional dengan teknik tatah sungging yang halus. Telah mewariskan keahlian turun temurun.',
    description_en: 'Traditional leather puppet maker with fine carving and painting techniques. Inherited skills passed down through generations.',
    products: [
      {
        name_id: 'Wayang Kulit Tokoh Pandawa',
        name_en: 'Pandawa Character Puppet',
        price_range: 'Rp 1.500.000 - Rp 5.000.000',
      },
      {
        name_id: 'Miniatur Wayang',
        name_en: 'Miniature Puppet',
        price_range: 'Rp 150.000 - Rp 500.000',
      },
    ],
    images: ['/mock/wayang1.jpg', '/mock/wayang2.jpg'],
    featured_image: '/mock/wayang1.jpg',
    contact: {
      phone: '081345678901',
      email: 'wayangkulit.hadi@gmail.com',
    },
    location: {
      address: 'Kampung Dagen, Patehan, Kraton, Yogyakarta',
    },
    social_media: {},
    status: 'published',
    featured: false,
    verified: true,
    published_at: new Date('2024-02-01'),
    created_at: new Date('2024-01-25'),
    updated_at: new Date('2024-02-05'),
  },
  {
    id: '4',
    slug: 'bakpia-pathok-25',
    business_name: 'Bakpia Pathok 25',
    owner_name: 'Bapak Sutarno',
    category: 'Kuliner',
    description_id: 'Produsen bakpia khas Yogyakarta dengan berbagai varian rasa. Menggunakan bahan-bahan berkualitas dan proses higienis.',
    description_en: 'Producer of Yogyakarta\'s signature bakpia with various flavor variants. Using quality ingredients and hygienic processes.',
    products: [
      {
        name_id: 'Bakpia Kacang Hijau',
        name_en: 'Mung Bean Bakpia',
        price_range: 'Rp 50.000/box',
      },
      {
        name_id: 'Bakpia Coklat',
        name_en: 'Chocolate Bakpia',
        price_range: 'Rp 55.000/box',
      },
      {
        name_id: 'Bakpia Keju',
        name_en: 'Cheese Bakpia',
        price_range: 'Rp 60.000/box',
      },
    ],
    images: ['/mock/bakpia1.jpg'],
    featured_image: '/mock/bakpia1.jpg',
    contact: {
      phone: '0274588888',
      whatsapp: '081234999888',
      email: 'bakpiapathok25@gmail.com',
    },
    location: {
      address: 'Jl. KH. Ali Maksum, Krapyak, Yogyakarta',
    },
    social_media: {
      instagram: '@bakpiapathok25',
      website: 'https://bakpiapathok25.com',
    },
    operating_hours: {
      open_time: '08:00',
      close_time: '21:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    status: 'published',
    featured: true,
    verified: true,
    published_at: new Date('2024-01-20'),
    created_at: new Date('2024-01-15'),
    updated_at: new Date('2024-02-10'),
  },
  {
    id: '5',
    slug: 'keris-pusaka-jogja',
    business_name: 'Keris Pusaka Jogja',
    owner_name: 'Mas Agung Prasetyo',
    category: 'Kerajinan',
    description_id: 'Pengrajin keris tradisional dengan teknik pembuatan yang autentik. Tersedia berbagai jenis keris dengan pamor yang indah.',
    description_en: 'Traditional keris craftsman with authentic manufacturing techniques. Various types of keris with beautiful damascus patterns available.',
    products: [
      {
        name_id: 'Keris Luk 7',
        name_en: '7-Wave Keris',
        price_range: 'Rp 5.000.000 - Rp 15.000.000',
      },
      {
        name_id: 'Keris Lurus',
        name_en: 'Straight Keris',
        price_range: 'Rp 3.000.000 - Rp 10.000.000',
      },
    ],
    images: ['/mock/keris1.jpg'],
    featured_image: '/mock/keris1.jpg',
    contact: {
      phone: '081567890123',
      email: 'kerispusaka@yahoo.com',
    },
    location: {
      address: 'Kotagede, Yogyakarta',
    },
    social_media: {
      facebook: 'KerisPusakaJogja',
    },
    status: 'draft',
    featured: false,
    verified: false,
    created_at: new Date('2024-02-15'),
    updated_at: new Date('2024-02-16'),
  },
  {
    id: '6',
    slug: 'silverware-kotagede',
    business_name: 'Silverware Kotagede',
    owner_name: 'Pak Bambang Riyanto',
    category: 'Kerajinan',
    description_id: 'Pengrajin perhiasan dan kerajinan perak khas Kotagede. Menerima custom design dan pesanan khusus.',
    description_en: 'Silver jewelry and craft artisan typical of Kotagede. Accepts custom designs and special orders.',
    products: [
      {
        name_id: 'Cincin Perak',
        name_en: 'Silver Ring',
        price_range: 'Rp 150.000 - Rp 1.000.000',
      },
      {
        name_id: 'Bros Perak',
        name_en: 'Silver Brooch',
        price_range: 'Rp 200.000 - Rp 800.000',
      },
      {
        name_id: 'Miniatur Perak',
        name_en: 'Silver Miniature',
        price_range: 'Rp 500.000 - Rp 3.000.000',
      },
    ],
    images: ['/mock/silver1.jpg', '/mock/silver2.jpg'],
    featured_image: '/mock/silver1.jpg',
    contact: {
      phone: '0274377777',
      whatsapp: '085678901234',
    },
    location: {
      address: 'Jl. Mondorakan, Kotagede, Yogyakarta',
      coordinates: { lat: -7.8275, lng: 110.3987 },
    },
    social_media: {
      instagram: '@silverware_kotagede',
    },
    operating_hours: {
      open_time: '09:00',
      close_time: '17:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    status: 'published',
    featured: false,
    verified: true,
    published_at: new Date('2024-02-05'),
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2024-02-12'),
  },
  {
    id: '7',
    slug: 'angkringan-lik-man',
    business_name: 'Angkringan Lik Man',
    owner_name: 'Lik Man',
    category: 'Kuliner',
    description_id: 'Angkringan legendaris di Tugu Yogyakarta. Menu favorit mahasiswa dan wisatawan dengan harga terjangkau.',
    description_en: 'Legendary angkringan at Tugu Yogyakarta. Favorite menu of students and tourists with affordable prices.',
    products: [
      {
        name_id: 'Nasi Kucing',
        name_en: 'Cat Rice',
        price_range: 'Rp 3.000',
      },
      {
        name_id: 'Sate Usus',
        name_en: 'Intestine Satay',
        price_range: 'Rp 2.000',
      },
      {
        name_id: 'Wedang Jahe',
        name_en: 'Ginger Drink',
        price_range: 'Rp 5.000',
      },
    ],
    images: ['/mock/angkringan1.jpg'],
    featured_image: '/mock/angkringan1.jpg',
    contact: {
      phone: '081390123456',
    },
    location: {
      address: 'Jl. Jend. Sudirman (dekat Tugu), Yogyakarta',
      coordinates: { lat: -7.7830, lng: 110.3669 },
    },
    social_media: {},
    operating_hours: {
      open_time: '18:00',
      close_time: '02:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    status: 'published',
    featured: true,
    verified: true,
    published_at: new Date('2024-01-25'),
    created_at: new Date('2024-01-20'),
    updated_at: new Date('2024-02-08'),
  },
  {
    id: '8',
    slug: 'lurik-sutra-ibu-siti',
    business_name: 'Lurik Sutra Ibu Siti',
    owner_name: 'Ibu Siti Aminah',
    category: 'Fashion',
    description_id: 'Tenun lurik kombinasi sutra dengan motif tradisional. Tersedia kain dan produk jadi seperti tas dan dompet.',
    description_en: 'Lurik weaving combined with silk in traditional motifs. Available fabric and finished products like bags and wallets.',
    products: [
      {
        name_id: 'Kain Lurik Sutra',
        name_en: 'Silk Lurik Fabric',
        price_range: 'Rp 300.000 - Rp 800.000',
      },
      {
        name_id: 'Tas Lurik',
        name_en: 'Lurik Bag',
        price_range: 'Rp 150.000 - Rp 400.000',
      },
    ],
    images: ['/mock/lurik1.jpg'],
    featured_image: '/mock/lurik1.jpg',
    contact: {
      phone: '085712345678',
      whatsapp: '085712345678',
    },
    location: {
      address: 'Imogiri, Bantul, Yogyakarta',
    },
    social_media: {
      instagram: '@luriksutra_siti',
    },
    status: 'published',
    featured: false,
    verified: true,
    published_at: new Date('2024-02-10'),
    created_at: new Date('2024-02-05'),
    updated_at: new Date('2024-02-11'),
  },
];
