import { Wisata } from '../types';

export const mockWisataData: Wisata[] = [
  {
    id: '1',
    slug: 'pantai-parangtritis',
    name_id: 'Pantai Parangtritis',
    name_en: 'Parangtritis Beach',
    description_id: 'Pantai legendaris dengan pemandangan sunset menakjubkan, pasir hitam vulkanik, dan ombak yang megah. Dipercaya sebagai gerbang menuju istana Nyi Roro Kidul.',
    description_en: 'Legendary beach with stunning sunset views, volcanic black sand, and magnificent waves. Believed to be the gateway to the palace of Nyi Roro Kidul.',
    category: 'Alam',
    address: 'Desa Parangtritis, Kretek',
    district: 'Bantul',
    coordinates: { lat: -8.0247, lng: 110.3293 },
    images: ['/mock/parangtritis1.jpg', '/mock/parangtritis2.jpg', '/mock/parangtritis3.jpg'],
    featured_image: 'https://images.unsplash.com/photo-1655793488799-1ffba5b22cbd?w=800&q=80',
    operating_hours: {
      open_time: '06:00',
      close_time: '18:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 10000,
    contact: { phone: '081234567890' },
    facilities_id: ['Parkir', 'Toilet', 'Warung Makan', 'Penginapan', 'Persewaan ATV', 'Area Camping', 'Mushola'],
    facilities_en: ['Parking', 'Restrooms', 'Food Stalls', 'Accommodation', 'ATV Rental', 'Camping Area', 'Mushola'],
    activities: ['Bermain Layang-layang', 'Naik Kuda', 'ATV', 'Fotografi', 'Sunset Viewing'],
    difficulty_level: 'Easy',
    duration: '2-4 jam',
    best_visit_time: 'Sore hari (15:00-18:00) untuk menikmati sunset',
    tips_id: 'Hindari berenang karena ombak sangat besar. Jangan mengenakan pakaian hijau (kepercayaan lokal). Bawa topi dan sunscreen.',
    tips_en: 'Avoid swimming due to very large waves. Do not wear green clothes (local belief). Bring a hat and sunscreen.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-10'),
    created_at: new Date('2024-01-05'),
    updated_at: new Date('2024-02-15'),
  },
  {
    id: '2',
    slug: 'alun-alun-kidul',
    name_id: 'Alun-Alun Kidul',
    name_en: 'South Square',
    description_id: 'Lapangan terbuka dengan pohon beringin kembar yang ikonik. Terkenal dengan tradisi "Masangin" - berjalan dengan mata tertutup melewati dua pohon beringin. Area kuliner malam yang ramai.',
    description_en: 'Open square with iconic twin banyan trees. Famous for "Masangin" tradition - walking blindfolded between two banyan trees. Bustling night culinary area.',
    category: 'Budaya',
    address: 'Jl. Patehan Lor, Patehan',
    district: 'Kraton',
    coordinates: { lat: -7.8113, lng: 110.3642 },
    images: ['/mock/alkid1.jpg', '/mock/alkid2.jpg'],
    featured_image: 'https://images.unsplash.com/photo-1721747994983-96d23e197487?w=800&q=80',
    operating_hours: {
      open_time: '00:00',
      close_time: '23:59',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'free',
    contact: { phone: '0274373721' },
    facilities_id: ['Area Parkir', 'Penerangan', 'Food Court', 'Toilet Umum'],
    facilities_en: ['Parking Area', 'Lighting', 'Food Court', 'Public Restrooms'],
    activities: ['Masangin', 'Kuliner Malam', 'Fotografi', 'Naik Becak Hias'],
    difficulty_level: 'Easy',
    duration: '1-2 jam',
    best_visit_time: 'Malam hari (19:00-22:00) untuk suasana ramai dan kuliner',
    tips_id: 'Coba tradisi Masangin! Tawar harga sebelum sewa becak hias. Jaga barang berharga saat ramai.',
    tips_en: 'Try the Masangin tradition! Bargain before renting decorated pedicabs. Keep valuables safe when crowded.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-12'),
    created_at: new Date('2024-01-08'),
    updated_at: new Date('2024-02-20'),
  },
  {
    id: '3',
    slug: 'keraton-yogyakarta',
    name_id: 'Keraton Yogyakarta',
    name_en: 'Yogyakarta Palace',
    description_id: 'Istana Sultan yang masih berfungsi hingga kini. Kunjungi museum, saksikan pertunjukan tari dan gamelan, dan pelajari arsitektur Jawa tradisional yang megah.',
    description_en: "The Sultan's palace still in use today. Visit museums, watch dance and gamelan performances, and learn about magnificent traditional Javanese architecture.",
    category: 'Sejarah',
    address: 'Jl. Rotowijayan Blok No. 1, Panembahan',
    district: 'Kraton',
    coordinates: { lat: -7.8053, lng: 110.3644 },
    images: ['/mock/keraton1.jpg', '/mock/keraton2.jpg'],
    featured_image: '/assets/e68ea45479378a6003bae5ab6b785184768f6914.png',
    operating_hours: {
      open_time: '08:00',
      close_time: '14:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 15000,
    contact: { phone: '0274373721', email: 'info@kratonjogja.id' },
    facilities_id: ['Museum', 'Guide', 'Gift Shop', 'Audio Tour'],
    facilities_en: ['Museum', 'Guide', 'Gift Shop', 'Audio Tour'],
    activities: ['Tur Museum', 'Pertunjukan Tari', 'Gamelan', 'Fotografi'],
    difficulty_level: 'Easy',
    duration: '2-3 jam',
    best_visit_time: 'Pagi hari (08:00-11:00) untuk menghindari panas dan keramaian',
    tips_id: 'Berpakaian sopan (tidak ketat/pendek). Gunakan jasa guide resmi. Jangan lupa kunjungi museum kereta kencana.',
    tips_en: 'Dress modestly (not tight/short). Use official guide services. Don\'t forget to visit the royal carriage museum.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-15'),
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-02-25'),
  },
  {
    id: '4',
    slug: 'malioboro',
    name_id: 'Malioboro',
    name_en: 'Malioboro Street',
    description_id: 'Jantung wisata belanja Yogyakarta. Jalanan ikonik dengan batik, kerajinan tangan, kuliner khas, dan pertunjukan jalanan. Pengalaman berbelanja yang tak terlupakan.',
    description_en: 'The heart of Yogyakarta shopping tourism. Iconic street with batik, handicrafts, local cuisine, and street performances. An unforgettable shopping experience.',
    category: 'Belanja',
    address: 'Jl. Malioboro',
    district: 'Yogyakarta',
    coordinates: { lat: -7.7926, lng: 110.3656 },
    images: ['/mock/malioboro1.jpg', '/mock/malioboro2.jpg'],
    featured_image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    operating_hours: {
      open_time: '00:00',
      close_time: '23:59',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'free',
    contact: { phone: '0274562811' },
    facilities_id: ['Toko', 'ATM', 'Hotel', 'Restoran'],
    facilities_en: ['Shops', 'ATM', 'Hotels', 'Restaurants'],
    activities: ['Belanja Batik', 'Kuliner Kaki Lima', 'Naik Andong', 'Street Photography'],
    difficulty_level: 'Easy',
    duration: '2-4 jam',
    best_visit_time: 'Malam hari (18:00-22:00) untuk suasana ramai dan kuliner malam',
    tips_id: 'Tawar harga sebelum membeli. Jaga barang berharga. Coba kuliner kaki lima seperti gudeg, angkringan.',
    tips_en: 'Bargain before buying. Keep valuables safe. Try street food like gudeg, angkringan.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-02-01'),
    created_at: new Date('2024-01-28'),
    updated_at: new Date('2024-02-28'),
  },
  {
    id: '5',
    slug: 'tugu-yogyakarta',
    name_id: 'Tugu Yogyakarta',
    name_en: 'Yogyakarta Monument',
    description_id: 'Monumen ikonik yang menjadi landmark kota. Simbol perlawanan rakyat Yogyakarta. Area publik yang indah untuk foto dan bersantai.',
    description_en: "Iconic monument that serves as the city's landmark. Symbol of Yogyakarta people's resistance. Beautiful public area for photos and relaxation.",
    category: 'Sejarah',
    address: 'Jl. Jend. Sudirman',
    district: 'Yogyakarta',
    coordinates: { lat: -7.7831, lng: 110.3667 },
    images: ['/mock/tugu1.jpg', '/mock/tugu2.jpg'],
    featured_image: '/assets/9f169dd83a8981e7aedcf8dbab93b79692f0d10d.png',
    operating_hours: {
      open_time: '00:00',
      close_time: '23:59',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'free',
    facilities_id: ['Taman', 'Spot Foto', 'Penerangan', 'Akses Mudah'],
    facilities_en: ['Park', 'Photo Spots', 'Lighting', 'Easy Access'],
    activities: ['Fotografi', 'Bersantai', 'Menikmati Pemandangan Malam'],
    difficulty_level: 'Easy',
    duration: '30 menit - 1 jam',
    best_visit_time: 'Malam hari untuk melihat pencahayaan yang indah',
    tips_id: 'Hati-hati saat menyeberang jalan. Waktu terbaik foto adalah saat golden hour atau malam hari.',
    tips_en: 'Be careful when crossing the street. Best time to take photos is during golden hour or at night.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-20'),
    created_at: new Date('2024-01-15'),
    updated_at: new Date('2024-02-22'),
  },
  {
    id: '6',
    slug: 'benteng-vredeburg',
    name_id: 'Museum Benteng Vredeburg',
    name_en: 'Fort Vredeburg Museum',
    description_id: 'Benteng bersejarah yang kini menjadi museum. Pelajari sejarah perjuangan kemerdekaan Indonesia melalui diorama dan pameran interaktif.',
    description_en: "Historic fort now serving as a museum. Learn about Indonesia's independence struggle through dioramas and interactive exhibitions.",
    category: 'Sejarah',
    address: 'Jl. Margo Mulyo No.6',
    district: 'Yogyakarta',
    coordinates: { lat: -7.7992, lng: 110.3658 },
    images: ['/mock/vredeburg1.jpg', '/mock/vredeburg2.jpg'],
    featured_image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80',
    operating_hours: {
      open_time: '08:00',
      close_time: '16:00',
      days: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 3000,
    contact: { phone: '0274586934' },
    facilities_id: ['Museum', 'Perpustakaan', 'Auditorium', 'Kantin'],
    facilities_en: ['Museum', 'Library', 'Auditorium', 'Canteen'],
    activities: ['Tur Museum', 'Melihat Diorama', 'Belajar Sejarah', 'Fotografi'],
    difficulty_level: 'Easy',
    duration: '1-2 jam',
    best_visit_time: 'Pagi hingga siang hari. Tutup hari Senin.',
    tips_id: 'Baca informasi di setiap diorama dengan seksama. Sangat edukatif untuk pelajar.',
    tips_en: 'Read information at each diorama carefully. Very educational for students.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-02-05'),
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2024-03-01'),
  },
  {
    id: '7',
    slug: 'taman-sari',
    name_id: 'Taman Sari',
    name_en: 'Taman Sari Water Castle',
    description_id: 'Kompleks taman air bekas istana Sultan. Arsitektur unik perpaduan Jawa dan Eropa. Kolam pemandian, terowongan bawah tanah, dan Sumur Gumuling yang misterius.',
    description_en: "Former Sultan's water palace complex. Unique architecture blending Javanese and European styles. Bathing pools, underground tunnels, and the mysterious Sumur Gumuling.",
    category: 'Sejarah',
    address: 'Jl. Taman, Kraton',
    district: 'Kraton',
    coordinates: { lat: -7.8103, lng: 110.3594 },
    images: ['/mock/tamansari1.jpg', '/mock/tamansari2.jpg'],
    featured_image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&q=80',
    operating_hours: {
      open_time: '09:00',
      close_time: '15:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 15000,
    contact: { phone: '0274373721' },
    facilities_id: ['Guide', 'Toilet', 'Spot Foto', 'Parkir'],
    facilities_en: ['Guide', 'Restrooms', 'Photo Spots', 'Parking'],
    activities: ['Tur Sejarah', 'Fotografi', 'Menjelajah Terowongan'],
    difficulty_level: 'Easy',
    duration: '1-2 jam',
    best_visit_time: 'Pagi hari untuk menghindari keramaian',
    tips_id: 'Gunakan jasa guide lokal untuk cerita yang lebih lengkap. Hati-hati di area terowongan.',
    tips_en: 'Use local guide services for more complete stories. Be careful in tunnel areas.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-02-10'),
    created_at: new Date('2024-02-08'),
    updated_at: new Date('2024-03-05'),
  },
  {
    id: '8',
    slug: 'candi-prambanan',
    name_id: 'Candi Prambanan',
    name_en: 'Prambanan Temple',
    description_id: 'Kompleks candi Hindu terbesar di Indonesia. Warisan Dunia UNESCO dengan relief cerita Ramayana yang memukau. Pertunjukan Ramayana Ballet setiap malam.',
    description_en: 'The largest Hindu temple complex in Indonesia. UNESCO World Heritage Site with stunning Ramayana reliefs. Ramayana Ballet performances every night.',
    category: 'Religi',
    address: 'Jl. Raya Jogja - Solo KM 16, Prambanan',
    district: 'Sleman',
    coordinates: { lat: -7.7521, lng: 110.4914 },
    images: ['/mock/prambanan1.jpg', '/mock/prambanan2.jpg', '/mock/prambanan3.jpg'],
    featured_image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80',
    operating_hours: {
      open_time: '06:00',
      close_time: '17:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 50000,
    contact: { phone: '0274496401', email: 'info@borobudurpark.com' },
    facilities_id: ['Museum', 'Guide', 'Restoran', 'Teater'],
    facilities_en: ['Museum', 'Guide', 'Restaurant', 'Theater'],
    activities: ['Tur Candi', 'Melihat Relief', 'Ramayana Ballet', 'Fotografi'],
    difficulty_level: 'Easy',
    duration: '2-4 jam',
    best_visit_time: 'Sore hari (15:00-17:00) untuk sunset atau malam untuk Ramayana Ballet',
    tips_id: 'Beli tiket terusan untuk Ramayana Ballet. Pakai sepatu nyaman. Bawa air minum.',
    tips_en: 'Buy combined ticket for Ramayana Ballet. Wear comfortable shoes. Bring drinking water.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-12'),
    created_at: new Date('2024-01-08'),
    updated_at: new Date('2024-02-15'),
  },
  {
    id: '9',
    slug: 'kaliurang',
    name_id: 'Kaliurang',
    name_en: 'Kaliurang',
    description_id: 'Kawasan wisata pegunungan yang sejuk di lereng Gunung Merapi. Udara segar, pemandangan alam, dan berbagai aktivitas outdoor seperti hiking dan camping.',
    description_en: "Cool mountain resort area on Mount Merapi's slopes. Fresh air, natural scenery, and various outdoor activities like hiking and camping.",
    category: 'Alam',
    address: 'Kaliurang, Hargobinangun',
    district: 'Sleman',
    coordinates: { lat: -7.5992, lng: 110.4167 },
    images: ['/mock/kaliurang1.jpg', '/mock/kaliurang2.jpg'],
    featured_image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    operating_hours: {
      open_time: '00:00',
      close_time: '23:59',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'free',
    contact: { phone: '0274895463' },
    facilities_id: ['Hotel', 'Restoran', 'Jalur Hiking', 'Area Camping'],
    facilities_en: ['Hotels', 'Restaurants', 'Hiking Trails', 'Camping Areas'],
    activities: ['Hiking', 'Tracking', 'Camping', 'Outbound', 'Kuliner'],
    difficulty_level: 'Moderate',
    duration: '4-8 jam atau menginap',
    best_visit_time: 'Akhir pekan untuk suasana liburan atau weekday untuk lebih tenang',
    tips_id: 'Bawa jaket tebal karena suhu dingin (15-20 derajat). Cek status Gunung Merapi sebelum berkunjung.',
    tips_en: 'Bring a thick jacket as it is cold (15-20 degrees). Check Mount Merapi status before visiting.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-02-05'),
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2024-02-22'),
  },
  {
    id: '10',
    slug: 'goa-jomblang',
    name_id: 'Goa Jomblang',
    name_en: 'Jomblang Cave',
    description_id: 'Goa vertikal spektakuler dengan cahaya surga (heavenly light) yang menembus celah goa pada waktu tertentu. Petualangan caving yang menakjubkan.',
    description_en: 'Spectacular vertical cave with heavenly light penetrating the cave gap at certain times. An amazing caving adventure.',
    category: 'Petualangan',
    address: 'Desa Pacarejo, Semanu',
    district: 'Gunungkidul',
    coordinates: { lat: -8.0533, lng: 110.6833 },
    images: ['/mock/jomblang1.jpg', '/mock/jomblang2.jpg'],
    featured_image: '/mock/jomblang1.jpg',
    operating_hours: {
      open_time: '06:00',
      close_time: '14:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 450000,
    contact: { phone: '081328888899', whatsapp: '081328888899' },
    facilities_id: ['Toilet', 'Parkir', 'Mushola', 'Warung', 'Peralatan Safety', 'Guide Profesional'],
    facilities_en: ['Restrooms', 'Parking', 'Mushola', 'Food Stalls', 'Safety Equipment', 'Professional Guide'],
    activities: ['Vertical Caving', 'Fotografi', 'Cave Exploration'],
    difficulty_level: 'Hard',
    duration: '4-5 jam',
    best_visit_time: 'Pagi hari (10:00-12:00) untuk melihat cahaya surga',
    tips_id: 'Reservasi wajib H-1. Kondisi fisik harus prima. Pakai sepatu tracking. Bawa pakaian ganti.',
    tips_en: 'Reservation required H-1. Physical condition must be prime. Wear tracking shoes. Bring change of clothes.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-15'),
    created_at: new Date('2024-01-12'),
    updated_at: new Date('2024-02-20'),
  },
  {
    id: '11',
    slug: 'hutan-pinus-mangunan',
    name_id: 'Hutan Pinus Mangunan',
    name_en: 'Mangunan Pine Forest',
    description_id: 'Hutan pinus yang sejuk dan asri dengan spot foto instagramable. Pemandangan pegunungan Menoreh dari gardu pandang sangat memukau.',
    description_en: 'Cool and beautiful pine forest with instagrammable photo spots. The view of the Menoreh mountains from the viewing post is stunning.',
    category: 'Alam',
    address: 'Dlingo',
    district: 'Bantul',
    coordinates: { lat: -7.9394, lng: 110.4281 },
    images: ['/mock/mangunan1.jpg', '/mock/mangunan2.jpg', '/mock/mangunan3.jpg'],
    featured_image: '/mock/mangunan1.jpg',
    operating_hours: {
      open_time: '06:00',
      close_time: '17:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 5000,
    contact: { phone: '085643210987' },
    facilities_id: ['Toilet', 'Parkir', 'Warung', 'Gardu Pandang', 'Spot Foto', 'Area Piknik'],
    facilities_en: ['Restrooms', 'Parking', 'Food Stalls', 'Viewing Post', 'Photo Spots', 'Picnic Area'],
    activities: ['Fotografi', 'Piknik', 'Tracking Ringan', 'Bird Watching'],
    difficulty_level: 'Easy',
    duration: '2-3 jam',
    best_visit_time: 'Pagi hari (06:00-09:00) untuk udara segar dan kabut tipis yang indah',
    tips_id: 'Bawa jaket karena udara dingin. Datang pagi untuk menghindari keramaian. Jaga kebersihan hutan.',
    tips_en: 'Bring a jacket as it is cold. Come early to avoid crowds. Keep the forest clean.',
    featured: false,
    status: 'published',
    published_at: new Date('2024-01-20'),
    created_at: new Date('2024-01-18'),
    updated_at: new Date('2024-02-25'),
  },
  {
    id: '12',
    slug: 'gumuk-pasir-parangkusumo',
    name_id: 'Gumuk Pasir Parangkusumo',
    name_en: 'Parangkusumo Sand Dunes',
    description_id: 'Gurun pasir satu-satunya di Asia Tenggara dengan pemandangan mirip padang pasir. Spot foto unik dan aktivitas sandboarding.',
    description_en: 'The only sand desert in Southeast Asia with views like a desert. Unique photo spot and sandboarding activities.',
    category: 'Alam',
    address: 'Parangkusumo, Kretek',
    district: 'Bantul',
    coordinates: { lat: -8.0258, lng: 110.3131 },
    images: ['/mock/gumuk1.jpg', '/mock/gumuk2.jpg', '/mock/gumuk3.jpg'],
    featured_image: '/mock/gumuk1.jpg',
    operating_hours: {
      open_time: '06:00',
      close_time: '18:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 5000,
    contact: { phone: '081328567890' },
    facilities_id: ['Toilet', 'Parkir', 'Warung', 'Persewaan Sandboard', 'Persewaan Jeep'],
    facilities_en: ['Restrooms', 'Parking', 'Food Stalls', 'Sandboard Rental', 'Jeep Rental'],
    activities: ['Sandboarding', 'Jeep Tour', 'Fotografi', 'Sunset Viewing'],
    difficulty_level: 'Moderate',
    duration: '2-3 jam',
    best_visit_time: 'Sore hari (15:00-17:00) untuk menghindari panas terik dan menikmati sunset',
    tips_id: 'Bawa sunscreen dan topi. Pakai sepatu tertutup agar pasir tidak masuk. Air minum wajib dibawa.',
    tips_en: 'Bring sunscreen and hat. Wear closed shoes to prevent sand entry. Bring drinking water.',
    featured: false,
    status: 'published',
    published_at: new Date('2024-02-10'),
    created_at: new Date('2024-02-08'),
    updated_at: new Date('2024-03-01'),
  },
  {
    id: '13',
    slug: 'tebing-breksi',
    name_id: 'Tebing Breksi',
    name_en: 'Breksi Cliff',
    description_id: 'Bekas tambang batu kapur yang disulap menjadi destinasi wisata dengan ukiran relief pada tebing dan pemandangan kota Yogyakarta.',
    description_en: 'Former limestone quarry transformed into a tourist destination with relief carvings on the cliffs and views of Yogyakarta city.',
    category: 'Alam',
    address: 'Sambirejo, Prambanan',
    district: 'Sleman',
    coordinates: { lat: -7.7667, lng: 110.5000 },
    images: ['/mock/breksi1.jpg', '/mock/breksi2.jpg'],
    featured_image: '/mock/breksi1.jpg',
    operating_hours: {
      open_time: '06:00',
      close_time: '18:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 5000,
    facilities_id: ['Toilet', 'Parkir', 'Warung', 'Spot Foto', 'Gazebo'],
    facilities_en: ['Restrooms', 'Parking', 'Food Stalls', 'Photo Spots', 'Gazebo'],
    activities: ['Fotografi', 'Melihat Relief', 'Sunrise/Sunset Viewing'],
    difficulty_level: 'Easy',
    duration: '1-2 jam',
    best_visit_time: 'Pagi (sunrise) atau sore hari (sunset) untuk cahaya terbaik',
    tips_id: 'Hati-hati saat naik tangga dan di area tebing. Pakai alas kaki nyaman. Jaga kebersihan area wisata.',
    tips_en: 'Be careful on stairs and cliff areas. Wear comfortable footwear. Keep the tourist area clean.',
    featured: false,
    status: 'published',
    published_at: new Date('2024-03-05'),
    created_at: new Date('2024-03-01'),
    updated_at: new Date('2024-03-08'),
  },
];
