import { Wisata } from '../types';

export const mockWisataData: Wisata[] = [
  {
    id: '1',
    slug: 'pantai-parangtritis',
    name_id: 'Pantai Parangtritis',
    name_en: 'Parangtritis Beach',
    description_id: 'Pantai legendaris dengan pemandangan sunset menakjubkan, pasir hitam vulkanik, dan ombak yang megah. Dipercaya sebagai gerbang menuju istana Nyi Roro Kidul.',
    description_en: 'Legendary beach with stunning sunset views, volcanic black sand, and magnificent waves. Believed to be the gateway to the palace of Nyi Roro Kidul.',
    category: 'Alam',
    address: 'Desa Parangtritis, Kretek',
    district: 'Bantul',
    coordinates: { lat: -8.0247, lng: 110.3293 },
    images: ['/mock/parangtritis1.jpg', '/mock/parangtritis2.jpg', '/mock/parangtritis3.jpg'],
    featured_image: '/mock/parangtritis1.jpg',
    operating_hours: {
      open_time: '06:00',
      close_time: '18:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 10000,
    contact: { phone: '081234567890' },
    facilities: ['Toilet', 'Parkir Luas', 'Warung Makan', 'Persewaan ATV', 'Area Camping', 'Mushola'],
    activities: ['Bermain Layang-layang', 'Naik Kuda', 'ATV', 'Fotografi', 'Sunset Viewing'],
    difficulty_level: 'Easy',
    duration: '2-4 jam',
    best_visit_time: 'Sore hari (15:00-18:00) untuk menikmati sunset',
    tips_id: 'Hindari berenang karena ombak sangat besar. Jangan mengenakan pakaian hijau (kepercayaan lokal). Bawa topi dan sunscreen.',
    tips_en: 'Avoid swimming due to very large waves. Do not wear green clothes (local belief). Bring a hat and sunscreen.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-10'),
    created_at: new Date('2024-01-05'),
    updated_at: new Date('2024-02-15'),
  },
  {
    id: '2',
    slug: 'goa-jomblang',
    name_id: 'Goa Jomblang',
    name_en: 'Jomblang Cave',
    description_id: 'Goa vertikal spektakuler dengan cahaya surga (heavenly light) yang menembus celah goa pada waktu tertentu. Petualangan caving yang menakjubkan.',
    description_en: 'Spectacular vertical cave with heavenly light penetrating the cave gap at certain times. An amazing caving adventure.',
    category: 'Petualangan',
    address: 'Desa Pacarejo, Semanu',
    district: 'Gunungkidul',
    coordinates: { lat: -8.0533, lng: 110.6833 },
    images: ['/mock/jomblang1.jpg', '/mock/jomblang2.jpg'],
    featured_image: '/mock/jomblang1.jpg',
    operating_hours: {
      open_time: '06:00',
      close_time: '14:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 450000,
    contact: { phone: '081328888899', whatsapp: '081328888899' },
    facilities: ['Toilet', 'Parkir', 'Mushola', 'Warung', 'Peralatan Safety', 'Guide Profesional'],
    activities: ['Vertical Caving', 'Fotografi', 'Cave Exploration'],
    difficulty_level: 'Hard',
    duration: '4-5 jam',
    best_visit_time: 'Pagi hari (10:00-12:00) untuk melihat cahaya surga',
    tips_id: 'Reservasi wajib H-1. Kondisi fisik harus prima. Pakai sepatu tracking. Bawa pakaian ganti. Ikuti instruksi guide dengan ketat.',
    tips_en: 'Reservation required H-1. Physical condition must be prime. Wear tracking shoes. Bring change of clothes. Follow guide instructions strictly.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-15'),
    created_at: new Date('2024-01-12'),
    updated_at: new Date('2024-02-20'),
  },
  {
    id: '3',
    slug: 'hutan-pinus-mangunan',
    name_id: 'Hutan Pinus Mangunan',
    name_en: 'Mangunan Pine Forest',
    description_id: 'Hutan pinus yang sejuk dan asri dengan spot foto instagramable. Pemandangan pegunungan Menoreh dari gardu pandang sangat memukau.',
    description_en: 'Cool and beautiful pine forest with instagrammable photo spots. The view of the Menoreh mountains from the viewing post is stunning.',
    category: 'Alam',
    address: 'Dlingo',
    district: 'Bantul',
    coordinates: { lat: -7.9394, lng: 110.4281 },
    images: ['/mock/mangunan1.jpg', '/mock/mangunan2.jpg', '/mock/mangunan3.jpg'],
    featured_image: '/mock/mangunan1.jpg',
    operating_hours: {
      open_time: '06:00',
      close_time: '17:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 5000,
    contact: { phone: '085643210987' },
    facilities: ['Toilet', 'Parkir', 'Warung', 'Gardu Pandang', 'Spot Foto', 'Area Piknik'],
    activities: ['Fotografi', 'Piknik', 'Tracking Ringan', 'Bird Watching'],
    difficulty_level: 'Easy',
    duration: '2-3 jam',
    best_visit_time: 'Pagi hari (06:00-09:00) untuk udara segar dan kabut tipis yang indah',
    tips_id: 'Bawa jaket karena udara dingin. Datang pagi untuk menghindari keramaian. Jaga kebersihan hutan.',
    tips_en: 'Bring a jacket as it is cold. Come early to avoid crowds. Keep the forest clean.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-01-20'),
    created_at: new Date('2024-01-18'),
    updated_at: new Date('2024-02-25'),
  },
  {
    id: '4',
    slug: 'malioboro',
    name_id: 'Jalan Malioboro',
    name_en: 'Malioboro Street',
    description_id: 'Jantung kota Yogyakarta dengan deretan toko batik, pedagang kaki lima, dan suasana malam yang meriah. Wajib dikunjungi saat ke Jogja.',
    description_en: 'The heart of Yogyakarta city with rows of batik shops, street vendors, and lively night atmosphere. A must-visit when in Jogja.',
    category: 'Belanja',
    address: 'Jl. Malioboro',
    district: 'Yogyakarta',
    coordinates: { lat: -7.7926, lng: 110.3656 },
    images: ['/mock/malioboro1.jpg', '/mock/malioboro2.jpg'],
    featured_image: '/mock/malioboro1.jpg',
    operating_hours: {
      open_time: '00:00',
      close_time: '23:59',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'free',
    contact: { phone: '0274562811' },
    facilities: ['Toilet Umum', 'ATM', 'Transportasi Publik', 'Andong (Delman)', 'Becak'],
    activities: ['Belanja Batik', 'Kuliner Kaki Lima', 'Naik Andong', 'Street Photography'],
    difficulty_level: 'Easy',
    duration: '2-4 jam',
    best_visit_time: 'Malam hari (18:00-22:00) untuk suasana ramai dan kuliner malam',
    tips_id: 'Tawar harga sebelum membeli. Jaga barang berharga. Coba kuliner kaki lima seperti gudeg, angkringan. Pakai masker jika ramai.',
    tips_en: 'Bargain before buying. Keep valuables safe. Try street food like gudeg, angkringan. Wear a mask if crowded.',
    featured: true,
    status: 'published',
    published_at: new Date('2024-02-01'),
    created_at: new Date('2024-01-28'),
    updated_at: new Date('2024-02-28'),
  },
  {
    id: '5',
    slug: 'kaliurang',
    name_id: 'Kaliurang',
    name_en: 'Kaliurang Highland',
    description_id: 'Kawasan wisata pegunungan yang sejuk di lereng Gunung Merapi dengan pemandangan alam yang indah dan udara segar.',
    description_en: 'Cool mountain tourism area on the slopes of Mount Merapi with beautiful natural views and fresh air.',
    category: 'Alam',
    address: 'Kaliurang, Hargobinangun',
    district: 'Sleman',
    coordinates: { lat: -7.6000, lng: 110.4333 },
    images: ['/mock/kaliurang1.jpg', '/mock/kaliurang2.jpg'],
    featured_image: '/mock/kaliurang1.jpg',
    operating_hours: {
      open_time: '00:00',
      close_time: '23:59',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'free',
    contact: { phone: '0274895463' },
    facilities: ['Hotel', 'Villa', 'Restoran', 'Warung', 'Parkir', 'Toilet', 'Taman Rekreasi'],
    activities: ['Hiking', 'Tracking', 'Camping', 'Outbound', 'Kuliner'],
    difficulty_level: 'Moderate',
    duration: '4-8 jam atau menginap',
    best_visit_time: 'Akhir pekan untuk suasana liburan atau weekday untuk lebih tenang',
    tips_id: 'Bawa jaket tebal karena suhu dingin (15-20 derajat). Cek status Gunung Merapi sebelum berkunjung. Coba kuliner lokal seperti jadah tempe.',
    tips_en: 'Bring a thick jacket as it is cold (15-20 degrees). Check Mount Merapi status before visiting. Try local cuisine like jadah tempe.',
    featured: false,
    status: 'published',
    published_at: new Date('2024-02-05'),
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2024-02-22'),
  },
  {
    id: '6',
    slug: 'gumuk-pasir-parangkusumo',
    name_id: 'Gumuk Pasir Parangkusumo',
    name_en: 'Parangkusumo Sand Dunes',
    description_id: 'Gurun pasir satu-satunya di Asia Tenggara dengan pemandangan mirip padang pasir. Spot foto unik dan aktivitas sandboarding.',
    description_en: 'The only sand desert in Southeast Asia with views like a desert. Unique photo spot and sandboarding activities.',
    category: 'Alam',
    address: 'Parangkusumo, Kretek',
    district: 'Bantul',
    coordinates: { lat: -8.0258, lng: 110.3131 },
    images: ['/mock/gumuk1.jpg', '/mock/gumuk2.jpg', '/mock/gumuk3.jpg'],
    featured_image: '/mock/gumuk1.jpg',
    operating_hours: {
      open_time: '06:00',
      close_time: '18:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 5000,
    contact: { phone: '081328567890' },
    facilities: ['Toilet', 'Parkir', 'Warung', 'Persewaan Sandboard', 'Persewaan Jeep'],
    activities: ['Sandboarding', 'Jeep Tour', 'Fotografi', 'Sunset Viewing'],
    difficulty_level: 'Moderate',
    duration: '2-3 jam',
    best_visit_time: 'Sore hari (15:00-17:00) untuk menghindari panas terik dan menikmati sunset',
    tips_id: 'Bawa sunscreen dan topi. Pakai sepatu tertutup agar pasir tidak masuk. Air minum wajib dibawa. Hati-hati saat sandboarding.',
    tips_en: 'Bring sunscreen and hat. Wear closed shoes to prevent sand entry. Bring drinking water. Be careful when sandboarding.',
    featured: false,
    status: 'published',
    published_at: new Date('2024-02-10'),
    created_at: new Date('2024-02-08'),
    updated_at: new Date('2024-03-01'),
  },
  {
    id: '7',
    slug: 'tebing-breksi',
    name_id: 'Tebing Breksi',
    name_en: 'Breksi Cliff',
    description_id: 'Bekas tambang batu kapur yang disulap menjadi destinasi wisata dengan ukiran relief pada tebing dan pemandangan kota Yogyakarta.',
    description_en: 'Former limestone quarry transformed into a tourist destination with relief carvings on the cliffs and views of Yogyakarta city.',
    category: 'Alam',
    address: 'Sambirejo, Prambanan',
    district: 'Sleman',
    coordinates: { lat: -7.7667, lng: 110.5000 },
    images: ['/mock/breksi1.jpg', '/mock/breksi2.jpg'],
    featured_image: '/mock/breksi1.jpg',
    operating_hours: {
      open_time: '06:00',
      close_time: '18:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    },
    entry_fee_type: 'paid',
    entry_fee_amount: 5000,
    facilities: ['Toilet', 'Parkir', 'Warung', 'Spot Foto', 'Gazebo'],
    activities: ['Fotografi', 'Melihat Relief', 'Sunrise/Sunset Viewing'],
    difficulty_level: 'Easy',
    duration: '1-2 jam',
    best_visit_time: 'Pagi (sunrise) atau sore hari (sunset) untuk cahaya terbaik',
    tips_id: 'Hati-hati saat naik tangga dan di area tebing. Pakai alas kaki nyaman. Jaga kebersihan area wisata.',
    tips_en: 'Be careful on stairs and cliff areas. Wear comfortable footwear. Keep the tourist area clean.',
    featured: false,
    status: 'draft',
    created_at: new Date('2024-03-05'),
    updated_at: new Date('2024-03-08'),
  },
];
